### PR TITLE
.gitignore: Add DS_Store

### LINKED ISSUE #2067: Addition of DS_Store to .gitignore
DS_Store should be ignored in coala-bears just like it is already being ignored in coala.

### PR DESCRIPTION
**Pull request by RaiVaibhav**
File changed:  [.gitignore](https://github.com/coala/coala-bears/blob/master/.gitignore)
Changes : Add `.DS_Store`
Closes #2067

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
@prnvdixit i will change it asap

**Comment by prnvdixit** [comment]
Also, what exactly is ```Name of File changed .gitignore``` signifying? Have you changed the name of file (I don't think so :wink:)?

**Comment by RaiVaibhav** [comment]
@urohit011  apologies I mistakenly added your commit , i will change it as soon as possible

**Comment by RaiVaibhav** [comment]
Closing this PR as i accidentally deleted my FORK REPO

**Comment by stellargo** [comment]
@raivaibhav i think you already merged a newcomer issue right? Why dont you move on to difficulty/low since you are no longer a newcomer:P

**Comment by RaiVaibhav** [comment]
Sumit Sir i have given too much time on this because of my foolish mistake ,i request to consider me last time

**Comment by prnvdixit** [comment]
@stellargo Oh... Even I didn't considered it before reviewing... :sweat_smile: 
@RaiVaibhav I totally agree with @stellargo, as mostly newcomer issues are to introduce you to basic workflow and convention practices (which I am sure you have been introduced to in your first PR). Plus, finding a ```newcomer``` issue is tough - So, I will also recommend moving to higher difficulty issue and leave this one for some ```actual newcomer``` :stuck_out_tongue:  :+1:

**Comment by RaiVaibhav** [comment]
@prnvdixit  i already submitted my new PR

**Pull request closed without merging**
