### PR TITLE
CI: Use gometalinter installer

### PR DESCRIPTION
**Pull request by jayvdb**
gometalinter maintains its own forks

Closes https://github.com/coala/coala-bears/issues/2534

### CODE REVIEW

**Comment by jayvdb** [comment]
This failed because of the pytest-timeout problem fixed in https://gitlab.com/coala/mobans/merge_requests/32

**Comment by jayvdb** [comment]
This failed on the Travis Python 3.6 job because of a package version conflict in with `packaging`.

https://travis-ci.org/coala/coala-bears/jobs/392177216
```console
pkg_resources.ContextualVersionConflict: (packaging 17.1 (/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages), Requirement.parse('packaging~=16.8'), {'coala'})
```

It did pass on my fork
https://travis-ci.org/jayvdb/coala-bears/builds/392177175

Another solution is to move the coala-ci invocation to a separate job in the matrix, so its dependencies are separate.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/2536/commits/4fe7deeae0d252089928a571c013f38151d40518 https://github.com/coala/coala-bears/pull/2536/commits/66ceb781485fcc479740ed592729a2039e6a0bc4

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2536/commits/5585b77ebed137f69ea2b7e5425723e3b6a2ab75 https://github.com/coala/coala-bears/pull/2536/commits/8bb35cac066c49889a896e980d8417c841863d6e

**Pull request merged**
