### PR TITLE
.travis.yml: Change 'sudo:required' to 'sudo:enabled'

### LINKED ISSUE #2212: change `sudo: required` to `sudo: enabled` in .travis.yml file
image

### PR DESCRIPTION
**Pull request by surana-mudit**
Change the 'sudo : required' to 'sudo : enabled' in ".travis.yml" file

Closes #2212 

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by newbazz** [comment]
get the issue assigned to you. ;P

**Comment by surana-mudit** [comment]
@newbazz  I have already read that documentation and updated my commit message according to it.
Can you tell me where is the problem exactly?

**Comment by newbazz** [comment]
image
This is what ur commit msg sud be 
image
and this is what commit msg is

**Comment by surana-mudit** [comment]
@newbazz  I have changed the commit message. Have a look

**Comment by surana-mudit** [comment]
I can't think of any suitable commit msg which resolves the gitmate errors.
I think the gitmate errors are unrelated as one of it is saying 'required' is a bad word while it is needed in the commit msg

**Comment by newbazz** [comment]
There are three parts of a commit namely the heading, commit shortlog and the issue reference, you dont fulfill the requirement ;P

**Comment by surana-mudit** [comment]
I think I should create a new PR , as this is quite messed up. Can we close this one ?

**Comment by newbazz** [comment]
never close a PR ;P, edit this one

**Comment by Makman2** [comment]
@surana-mudit still on it?

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
