### PR TITLE
Fix several bears which violate 1-based line/column convention

### PR DESCRIPTION
**Pull request by li-boxuan**
Fix several bears which violate 1-based line/column convention

Fixes https://github.com/coala/coala-bears/issues/2563, https://github.com/coala/coala-bears/issues/2574, https://github.com/coala/coala-bears/issues/2573, https://github.com/coala/coala-bears/issues/2572, https://github.com/coala/coala-bears/issues/2562, https://github.com/coala/coala-bears/issues/2393

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
Interesting error on [Appveyor](https://ci.appveyor.com/project/coala/coala-bears/build/1.0.9457/job/ahx8a7awvoa5n0wv).  maybe different version of pylint there?

**Comment by li-boxuan** [comment]
Agree. I doubt there is some issue with pylint version. I would try different versions on my laptop.

**Comment by li-boxuan** [comment]
@jayvdb  So there is some inconsistency with pylint 1.8.4.

On Unix, running ```pylint test.py --disable ''``` would return output as if there is no ```--disable```flag

However, on windows, ```pylint test.py --disable ''``` would return error ```pylint: error: -d option requires 1 argument```

Just as the error message says, this option requires 1 argument. The old test case should be deleted.

**Comment by li-boxuan** [comment]
This is blocked by https://github.com/coala/coala/pull/5350

**Comment by jayvdb** [comment]
@li-boxuan Please rebase , and ideally include commits fixing https://github.com/coala/coala-bears/issues/2562 and https://github.com/coala/coala-bears/issues/2563 if they are straight forward fixes with `normalize_column_numbers`.  If they are not fixed by that, we need to work rather quickly to look for an alternative solution.

**Comment by jayvdb** [comment]
I've done testing on all of the bears failing for this reason, and they can all be fixed this way.
c.f. https://travis-ci.org/jayvdb/coala-bears/jobs/399852497
Please include them all in this patch.
There are a few other breakages, and given how critical this is I am tempted to merge with them broken which will cause all other PRs to be broken again until those other tests are fixed.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2413/commits/6906e5465123ecd46e41b603b725bb4d188a23c6 https://github.com/coala/coala-bears/pull/2413/commits/2acc60305c1051a79ffe1fef6ab8ad64e06a808e https://github.com/coala/coala-bears/pull/2413/commits/2762d135331bacec98b381b90caf8a773e94e14b https://github.com/coala/coala-bears/pull/2413/commits/2f6f58b4afa0b139aa25062c3d3fcb27df3ea0d5 https://github.com/coala/coala-bears/pull/2413/commits/1f3325519a72cb98669185149b03b11c1ec25f70 https://github.com/coala/coala-bears/pull/2413/commits/705f9db98d957cc9d27e675b1d58f369feb54255 https://github.com/coala/coala-bears/pull/2413/commits/e5df6bcac33aa06bec70bf21217972620c34e888  https://github.com/coala/coala-bears/pull/2413/commits/e445c04e28e95b7f21983e9e2dd770e81838aa69 https://github.com/coala/coala-bears/pull/2413/commits/401fa883ffbe21b78a8a4899160592a293f3d4cd

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2413/commits/d8741c56f94401e8247204b9f49efd39fc53bf70

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
