### PR TITLE
Update rstcheck version to 3.1

### PR DESCRIPTION
**Pull request by Josiah-DuBose**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Josiah-DuBose** [comment]
commit b7fb5c04b25ea6dd5608c52860205e010280f3e7 has the correct commit msg formatting. I apologize about the other two. Next time it will be cleaner!

**Comment by Josiah-DuBose** [comment]
commit b7fb5c04b25ea6dd5608c52860205e010280f3e7 has the commit msg formatting. I apologize about the other two. It will be cleaner next time.

**Comment by Josiah-DuBose** [comment]
commit b7fb5c04b25ea6dd5608c52860205e010280f3e7 has the correct msg formatting. I apologize about the other two.

**Comment by supergr35** [comment]
Uh-oh! You have have the dreaded merge commit. This is probably because you pushed the rebase(update branch from master) button in github. This is not the proper way of doing this and will break many things. Please do an interactive rebase on the commit before the merge commit and remove the merge commit line(see http://stackoverflow.com/questions/17577409/git-remove-merge-commit-from-history). See https://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing for the proper way to rebase.
(it's okay, we all make mistakes in git ;) )

Please squash these commits :)

**Comment by Josiah-DuBose** [comment]
My branch rejected my rebase every time for some reason. I've moved this to a branch/pull request that you can find here https://github.com/coala/coala-bears/pull/1722. Sorry for the hassle...

**Pull request closed without merging**
