### PR TITLE
.ci/deps.sh: Fix infer breakage

### PR DESCRIPTION
**Pull request by jayvdb**
Fixes https://github.com/coala/coala-bears/issues/1763

### CODE REVIEW

**Comment by jayvdb** [comment]
Uncached build at https://travis-ci.org/jayvdb/coala-bears/builds/236023948

**Comment by Mixih** [comment]
ack ee28a84 4aa4c9e

**Comment by Mixih** [comment]
An alternative is being investigated

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
