### PR TITLE
.travis.yml: Remove sudo

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/coala/coala-bears/issues/2592

Unfortunately also adds more use of Travis CI's addon, which is a bit dodgy atm
https://github.com/coala/coala-bears/issues/2591

### CODE REVIEW

**Comment by jayvdb** [comment]
The tests almost passed on Circle.  A timeout issue https://circleci.com/gh/jayvdb/coala-bears/1001 I've started a new build.

**Comment by jayvdb** [comment]
The Python 3.6 Travis job has exceeded the time limit twice :/

**Comment by Makman2** [comment]
ack 8e08a74 e7959ad 05c9946 d513f69 60d9b82 cde5793

**Comment by yukiisbored** [comment]
reack

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2594/commits/903259ad2b3f3c7e57980b14e95aafa5d3d158de

**Comment by jayvdb** [comment]
gitmate is still down.  Manually merged.

**Pull request merged**
