### PR TITLE
KeywordBearTest: Add language setting in test

### PR DESCRIPTION
**Pull request by refeed**
Fixes https://github.com/coala/coala-bears/issues/1885

### CODE REVIEW

**Comment by jayvdb** [comment]
There is a coverage problem :-(

**Comment by refeed** [comment]
@jayvdb 
err, I think we could delete this code, since there's should be always a `dependency_results`:
from `KeywordBear.py:14`
```py
    if not dependency_results:
        return
```

**Comment by jayvdb** [comment]
> err, I think we could delete this code, since there's should be always a dependency_results:
from KeywordBear.py:14

Well, `if not` is currently also testing for an "empty" `dependency_results`.  Can it ever be empty?  Or, will it be filled with one dict member key "AnnotationBear" with a value of "no annotations"?

If `dependency_results` can be "false-ish" , there is likely a bug here anyway, as b8d38207261 added `list(..)`, which will be `list(None)` which raises `TypeError: 'NoneType' object is not iterable` .  Lines 17-20 also have a similar problem.

That commit comes from issue https://github.com/coala/coala-bears/issues/1274 , which didnt have any tests, but https://github.com/coala/coala-bears/issues/1306 was created for tests, and then https://github.com/coala/coala-bears/issues/1306 had tests but was closed without being merged.

So, I think it is very reasonable to remove `KeywordBear.py:14-15`.  That is the simple fix.

We could potentially skip all of the `KeywordBear` logic if there are no `dependency_results` containing comments, but it needs to be rewritten as `_get_comments` should return an empty list so that `list(..)` doesnt fail.  Then we would need a new test method to confirm (using mock) that the bear does not execute `check_keywords` if there was no comments  `dependency_results`, which will give you the extra coverage needed.

**Comment by refeed** [comment]
@jayvdb 
> Well, if not is currently also testing for an "empty" dependency_results. Can it ever be empty? Or, will it be filled with one dict member key "AnnotationBear" with a value of "no annotations"?

If `AnnotationBear` doesn't yield anything, `dependency_results` will be filled with one dict member `AnnotationBear` with value `[]`

**Comment by jayvdb** [comment]
ack 581827c 0340406 62daca6

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
