### PR TITLE
bear-requirements.txt: Bump pyflakes

### PR DESCRIPTION
**Pull request by MacBox7**
Upgrades pyflakes version to 2.0.0

Closes https://github.com/coala/coala-bears/issues/2621

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2641/commits/9a37397a58c820b28d8d706a49cefc847f963ddb

**Comment by jayvdb** [comment]
unack 9a37397

**Comment by jayvdb** [comment]
Based on https://gitlab.com/jayvdb/coala-pyflakes/-/jobs/84416570 , we need to ensure we have a test which has an error on line 1, to ensure that we have the right setting for 0 or 1 based line offsets.
Also the autoflake bear (PyUnusedCodeBear?).

If there is no test covering that, create an issue and fix pls.

**Comment by MacBox7** [comment]
This was handled in [commit](https://gitlab.com/MacBox7/coala-pyflakes-transfer/commit/2186ca6a8edd335e44b19ebc27a123b11f18f630). Forgot to mention here. The problem was that `python AST` starts `col_offset` from 0. Now the results are fixed in `coala-pyflakes`. A test case for the same has been added [here](https://gitlab.com/MacBox7/coala-pyflakes-transfer/commit/2186ca6a8edd335e44b19ebc27a123b11f18f630#2d358604624d41523f346259f93ffe2b86cf920f_2_1).

**Comment by jayvdb** [comment]
@MacBox7 , ideally we have tests in this repo which verify that the line/col offsets of the bears are correct.
All bears should have an error on line 1, and verify that the error reported is against line 1 and not against line 0.  Likewise with columns.

**Comment by MacBox7** [comment]
We can implement a method in LocalBearTestHelper that asserts for this.
```
def test_result_offset(self):
        if getattr(self, 'initial_offset_file', False):
            self.check_results(
                self.uut,
                self.initial_offset_file.splitlines(True),
                [Result.from_values(self.uut.__class__.__name__,
                                    self.initial_offset_message,
                                    file='test',
                                    line=1,
                                    column=1)],
                filename='test')
```

**Comment by jayvdb** [comment]
ack e46d352

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
