### PR TITLE
ApertiumLintBear: Fix typos

### PR DESCRIPTION
**Pull request by gokberksahin**
Changed the words `consits` -> `consists` and `Inconsitency`-> `Inconsistency`.

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@gokberksahin change the commit message of this PR. As suggested by the community on
the PR you had closed. It must follow the commit guidelines of coala.

**Comment by gokberksahin** [comment]
As @Makman2 said in the reference PR commit body is not needed. Please review and merge.

**Comment by mridubhatnagar** [comment]
who'll mention the filename? 
We had told you the changes there. I am not asking for the commit body.

**Comment by gokberksahin** [comment]
Made the necessary changes.

**Comment by Makman2** [comment]
> For trivial things a commit body is not required **(except the issue reference)**

please read things carefully^^

**Comment by gokberksahin** [comment]
Sorry, I don't get what you mean. Commit has issue reference.

**Comment by Makman2** [comment]
> As @Makman2 said in the reference PR commit body is not needed. 

I just wanted to make you aware to cite things properly, as this is not what I've said ;)

**Comment by Makman2** [comment]
ack d0e827b

**Comment by gokberksahin** [comment]
Yeah i know, commit body is needed, i meant for this particular PR.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
reack 207a140

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
