### PR TITLE
bears/css: Add PostCSSBear

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
This PR is not completely ready yet. There're two todos, though please take a look already :+1:

**Comment by Asnelchristian** [comment]
It looks sane to me

**Comment by Asnelchristian** [comment]
i am marking WIP the `todo` are done :)

**Comment by Adrianzatreanu** [comment]
@Makman2 buuump

**Comment by Makman2** [comment]
okay okay I'm on it ... :P

**Comment by sils** [comment]
@Makman2 ...?!?

**Comment by Makman2** [comment]
Too outdated.

**Pull request closed without merging**
