### PR TITLE
appveyor.yml: Install go dependencies

### LINKED ISSUE #42: Appveyor not installing go dependencies
_From @AbdealiJK on February 15, 2016 13:50_

https://ci.appveyor.com/project/sils1297/coala/build/1.0.3270

Says:
```
go get -u github.com/golang/lint/golint
package github.com/golang/lint/golint: directory "c:\\gopath\\src\\github.com\\golang\\lint\\golint" is not using a known version control system
```

_Copied from original issue: coala-analyzer/coala#1503_

### PR DESCRIPTION
**Pull request by Monal5031**
Installed Go dependencies on appveyor

Closes #42

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Monal5031** [comment]
@gitmate-bot rebase

**Comment by Monal5031** [comment]
@RaiVaibhav Thanks for your review but I already figured travis was failing due to some other issue. I myself added the PR as `wip` because was waiting for it be solved 😉

**Comment by RaiVaibhav** [comment]
unack a11f5072a2e0bdc94e5b9742aed8bc9b4fe73567

**Comment by Monal5031** [comment]
@gitmate-bot rebase

**Comment by Monal5031** [comment]
@RaiVaibhav All the tests pass now, please update your review.

**Comment by RaiVaibhav** [comment]
@Monal5031  need to know why we not use `depedency_management` here as it is including all the requirement needed here.

**Comment by RaiVaibhav** [comment]
ack 9900d4146cc4ae42c04682ab158d03c8e95d01eb

**Comment by Makman2** [comment]
Have you looked at tests whether they are not skipped now on Appveyor?

Also regarding commit message: Please remove "Installed Go dependencies in appveyor" in the body, this is super redundant ;)

**Comment by Makman2** [comment]
unack 5fd18f9

**Comment by Monal5031** [comment]
Sure will take a look once again and fix the commit message too :)

**Comment by Makman2** [comment]
Seems your changes had no effect:
```
tests\go\GoErrCheckBearTest.py ssssssssss                                [ 40%]
tests\go\GoImportsBearTest.py ss                                         [ 40%]
tests\go\GoLintBearTest.py ssss                                          [ 40%]
tests\go\GoReturnsBearTest.py ss                                         [ 41%]
tests\go\GoTypeBearTest.py ss                                            [ 41%]
tests\go\GoVetBearTest.py .                                              [ 41%]
tests\go\GofmtBearTest.py ..      
```
Like before on master :+1:

**Comment by Monal5031** [comment]
Yeah just noticed, weird 😕  let me see if I can do something .

**Comment by Monal5031** [comment]
Go deps are installed in a different way on windows than they do on linux, I haven't had much experience with windows. So closing this for now (will try to figure out a solution)

**Pull request closed without merging**
