### PR TITLE
CI: Cache Sphinx build directory

### PR DESCRIPTION
**Pull request by jayvdb**
Speeds up the builds.

### CODE REVIEW

**Comment by jayvdb** [comment]
Same as https://github.com/coala/coala/pull/4338

**Comment by jayvdb** [comment]
@mixih, do you know why we dont use Sphinx caching.
I remember we had some problem with the `make` command, but I think that is unrelated.

**Comment by jayvdb** [comment]
Over on https://github.com/coala/coala-bears/pull/1819#discussion_r120952016 , @userzimmermann has said:

> Removing `docs/API` is important to make autodoc always regenerate it from the python modules, what can lead to errors as we had them here... That should always be checked!

**Comment by jayvdb** [comment]
I've checked the custom `setup.py` commands `docs`, and it uses `sphinx-apidoc -f` which forces overwriting.  But that is quite unnecessary anyway, as the `docs/API` area is not cached between CI builds and it isnt generated in any earlier steps of the CI build, so `docs/API` is empty each CI build when (the next line) `python setup.py docs` is executed. (but even if it isnt, the `docs` command will clean it, so the `rm -rf docs/API` is absolutely useless, unless there is a bug in sphinx-autodoc's `-f`, which we should fix upstream.

**Comment by yash-nisar** [comment]
ack 210d78a6976585ce6e2f9105cc883614a73acbbb

**Comment by jayvdb** [comment]
reack 0650689

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
