### PR TITLE
README.rst : add language Stylus

### PR DESCRIPTION
**Pull request by appi147**
added Stylus to Languages Supported table
fixes https://github.com/coala/coala-bears/issues/1807

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by appi147** [comment]
> Shortlog of HEAD commit does not match given regex: ([^:]|[^:]+: [A-Z0-9].*)
I am not understanding this

**Comment by SanketDG** [comment]
@appi147 The first letter of the commit message after the colon should be a capital letter.

**Comment by appi147** [comment]
Sure

**Comment by IpshitaC** [comment]
As per the logs on [Travis CI](https://travis-ci.org/coala/coala-bears/jobs/249872418#L3678) and [AppVeyor](https://ci.appveyor.com/project/coala/coala-bears/build/1.0.7006/job/brqro48wgbe4b6gd#L577), the KeywordBearTest is not achieving 100% coverage. I can see the same for other PRs too.
But the latest commit has the build passing. And this branch also doesn't need any rebasing. Can anyone tell what might be the problem here?

**Comment by yash-nisar** [comment]
A fix is in progress, see https://github.com/coala/coala-bears/issues/1885. `coala-bears` is broken ATM.

**Comment by yash-nisar** [comment]
ack 6c23d27d955e99a5a5ba36e43699254463e45427

**Comment by IpshitaC** [comment]
Oh okay! Thanks for the info @yash-nisar :)

**Comment by IpshitaC** [comment]
ack 6c23d27d955e99a5a5ba36e43699254463e45427

**Comment by yash-nisar** [comment]
Can you rebase and push @appi147 ?

**Comment by appi147** [comment]
@yash-nisar Done

**Comment by yash-nisar** [comment]
The tests should pass now :)

**Comment by SanketDG** [comment]
reack bf88321

**Comment by SanketDG** [comment]
@rultor merge

**Pull request merged**
