### PR TITLE
package.json: Fix closing bracket indentation

### PR DESCRIPTION
**Pull request by shreyans800755**
This commit fixes indentation of closing bracket in
package.json file.

Closes https://github.com/coala/coala-bears/issues/1586

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
change looks fine, no idea why travis failed though. could you rebase please?

**Comment by shreyans800755** [comment]
Rebased, not sure why Travis and Circle CI is failing.

**Comment by jayvdb** [comment]
This is not a newcomer issue.  The file is generated, so the generator needs fixing.

**Comment by shreyans800755** [comment]
@jayvdb Can you please help me a bit more ?
`.ci/generate_bear_requirements.py` is running fine on my local, and producing following output:

> WARNING:root:StyleLintBear: Using unnecessary capturing groups affects the performance of coala. You should use '(?:<pattern>)' instead of '(<pattern>)' for your regex.
DEBUG:pip.vcs:Registered VCS backend: git
DEBUG:pip.vcs:Registered VCS backend: hg
DEBUG:pip.vcs:Registered VCS backend: svn
DEBUG:pip.vcs:Registered VCS backend: bzr
INFO:root:Generating grammar tables from /usr/lib/python3.4/lib2to3/Grammar.txt
INFO:root:Generating grammar tables from /usr/lib/python3.4/lib2to3/PatternGrammar.txt

I'm not sure, what needs to be updated in generator.

And according to failed Travis build, 
`git diff --exit-code bear-requirements.txt Gemfile package.json` is failing.
https://travis-ci.org/coala/coala-bears/jobs/227565464#L3863

**Comment by shreyans800755** [comment]
@jayvdb Can you help me move ahaed ?

**Comment by Mixih** [comment]
Please edit the file jayvdb specced.

**Comment by shreyans800755** [comment]
Accidentally closed PR. Created new one.

**Pull request closed without merging**
