### PR TITLE
RSTcheckBear.py: changed rstcheck to version 3.1

### PR DESCRIPTION
**Pull request by Josiah-DuBose**
bear_requirements: changed rstcheck to version 3.1

Updated version in both of the requested files.

Closes:https://github.com/coala/coala-bears/issues/1717

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
Please modify (using [`git amend`](http://coala.io/git#follow-up)) your commit message to comply with http://coala.io/commit

**Comment by Josiah-DuBose** [comment]
I've double checked and the only issues I saw was that I was missing the ".txt" on the bear_requirements file name and the two actions were listed as "changed" as opposed to "change". I've addressed these two things and as far as I can tell the commit message now complies entirely with the wiki.

**Comment by supergr35** [comment]
Make sure your commit message is correct locally and repush.

**Comment by Josiah-DuBose** [comment]
this is my commit both locally and on the remote: 
commit 2769e00edf490aefba34944571983a75722a1e7a
Author: Josiah DuBose <josiah7686@gmail.com>
Date:   Fri May 12 14:16:08 2017 -0400

    RSTcheckBear.py: change restcheck to version 3.1
    bear_requirements.txt: change rstcheck to version 3.1
    
    Updated version in both of the requested files.
    
    Closes:https://github.com/coala/coala-bears/issues/1717

This is the example commit message from your wiki:

setup.py: Change bears' entrypoint

This entrypoint ensures that coala discovers
the bears correctly.
It helps not writing more functions inside
``coalib`` for this.

Closes https://github.com/coala/coala/issues/5861

As far as I can tell I've followed this format. If there is still something wrong please be explicit about what it is so I can fix it.

**Comment by jayvdb** [comment]
@Josiah-DuBose ,
`Closes:https://github.com/coala/coala-bears/issues/1717`
should be
`Closes https://github.com/coala/coala-bears/issues/1717`

**Comment by jayvdb** [comment]
> ...: change rstcheck to version 3.1

should be

> ...: Change rstcheck to version 3.1

**Comment by jayvdb** [comment]
@Josiah-DuBose , see the message from the bot above.  It tells you the problem that needs fixing.

**Comment by supergr35** [comment]
One little nit: in your commit header you say `rest` but then in the body describe it as `rst`
Please use `rst` for both :+1:

**Comment by jayvdb** [comment]
ack 0127ee4

**Comment by jayvdb** [comment]
needs a rebase (then ping a maintainer in gitter)

**Comment by Josiah-DuBose** [comment]
What do you mean by needs a rebase? I have only one commit on my fork

**Comment by yash-nisar** [comment]
@Josiah-DuBose See http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing

**Comment by Josiah-DuBose** [comment]
I performed the rebase as per the instructions in your wiki and the response was "Already up to date". I must say this is the most lengthy and arduous commit process I've ever seen.

**Comment by yash-nisar** [comment]
Your branch `Update-rstcheck-version` is 4 commits behind master.

**Comment by yash-nisar** [comment]
We can resolve this on gitter if you're free. :)

**Comment by Josiah-DuBose** [comment]
When I pull I get up to date...I'm working on a branch off of my own fork and I'm not seeing any of the new commits from other users.

**Comment by yash-nisar** [comment]
ack 5e658a5d820be65daa0ed4bea2e1c00c3fc5bfab

**Comment by meetmangukiya** [comment]
@rultor merge

**Comment by supergr35** [comment]
Rultor isn't working too great ATM. We're trying to find a way to fix these problems.

**Comment by meetmangukiya** [comment]
@Josiah-DuBose please rebase

**Comment by yash-nisar** [comment]
@Josiah-DuBose Please ping us once you've rebased so we can merge this.

**Comment by jayvdb** [comment]
reack aa547dd

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
