### PR TITLE
SQLFormatBear.py: Add sqlparse bear

### PR DESCRIPTION
**Pull request by abhishalya**
Closes https://github.com/coala/coala-bears/issues/2406

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by li-boxuan** [comment]
@abhishalya   Ya, that would be better. For example, how do I know if the diff you provide is correct? What if the linter itself has a bug and does not provide correct verified code?

**Comment by abhishalya** [comment]
@li-boxuan I could, but there could be many examples here. It would depend upon the SQL syntax itself. There are many keywords and identifiers and verifying the output of linter on every part of the language would be difficult. And I think the output of the linter should've been verified on the linter repo already, so there is no actual need.

**Comment by abhishalya** [comment]
@li-boxuan The tests are already here: https://github.com/andialbrecht/sqlparse/tree/master/tests and they are passing, so the linter is working as expected.

**Comment by jayvdb** [comment]
ack 0b5972d

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
