### PR TITLE
PEP8NotebookBear.py: Spell mistake fix

### PR DESCRIPTION
**Pull request by Daronion**
In the PEP8NotebookBear.py file there was a spelling mistake at Line 11.
The change was needed for clearer understanding.

Closes https://github.com/coala/coala-bears/issues/2703

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Naveenaidu** [comment]
@Daronion The changes looks good to me :) 
Please fix your commit message. It does not follow the guidelines. Have a look at http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by Daronion** [comment]
@Naereen Thanks for the comment. Is it better now? The changes is noticed were
Fixes to Closes,
Spelling to imperative present Spell

**Comment by Daronion** [comment]
@ishanSrt Thanks for the review, I modified the body. Also, at the beginning I had itmarked as Fixes because I had read the documentation, but I thought this might have been a mistake so I changed it to Closes.

**Comment by Daronion** [comment]
@rishabhgarg25699 I asked to be assigned on this Issue at first the issue’s page. I waited for some time but I was still not assigned to the issue. I wanted to try making a request in order to learn how to make a PR so that I can contribute later on harder issues. I thought that since there was noone working on the issue and it is a newcomer issue there is no problem. I’m sorry for rushing

**Comment by Daronion** [comment]
@rishabhgarg25699 Yes I didn't notice that right away but now. I only saw there were no people assigned. Sorry for causing trouble, i'm closing this PR.

**Comment by Naveenaidu** [comment]
@Daronion No need to be sorry. It was an honest mistake. But I don't think you need to close the PR for this.

@rishabhgarg25699 As far as I think about there being another open PR by someone else. I don't think the other open PR can ever be considered. Though I appreciate his efforts for solving it.The other person has never claimed to be assigned to a task. Which I think is not correct approach. But on the other hand @Daronion did claim for the assignment of the issue before the other person if my knowledge serve me correctly. And then submitted a PR for it. I'm sure I have seen such cases where the person did submit a PR without assignment but was accepted only because he asked for assignment.

IMHO this PR needs to be Open and the other PR for the Issue must be closed. But then again, I would leave that to Maintainers. @jayvdb it's your call :)

@Daronion Please Open your PR again and wait till a maintainer comments on this. But please remember from next time on, `Do Not work on a Issue Until assigned`. If you want you can work on this issue on a separate  branch by asking to be assigned to the issue. And then if you find a solution for the issue. You can just comment on the issue about your approach, the maintainers will surely assign you the issue then.

P.S:- It's `@Naveen` not `@Naereen` :wink:

**Comment by rishabhgarg25699** [comment]
@ishanSrt @Daronion @Naveenaidu I am really very sorry for my hard language . I will remember this thing from next time and does not demotivate any newcomer.I once again Sorry @Daronion for my language.

**Comment by Daronion** [comment]
@Naveenaidu oops didn't mean to misspell your name, I think it must have autocompleted and I didn't notice. 
Thank you guys (Naveenaidu, ishanSrt, rishabhgarg25699) for taking your time to check this even if it is just a newcomer issue and it has no impact on the actual project. Helpful and active people is what I was hoping for since I'm willing to start documenting myself on this project so that I can solve greater issues. 
Didn't mean to cause any trouble or make you guys feel like you demotivated me. I was just not aware and didn't want to break any rules.

**Comment by RaiVaibhav** [comment]
@rishabhgarg25699 I think you really need to understand what review is
>Your changes and PR are good but tell me one thing How you are working on this issue. You are not assigned to this issue. Without assigning , you draft a PR . Also in the issue of this PR there was a reference a open PR but you ignore that and open your PR . Please follow the rules and regulations of the organisation.

Next time no such things in review, this is opensource no one is forced here, you need to remove your this type of review from all the PR you have reviewed (if any) and yeah like I said earlier please review your review first, you haven't done that.

**Comment by rishabhgarg25699** [comment]
> @rishabhgarg25699 I think you really need to understand what review is
> 
> > Your changes and PR are good but tell me one thing How you are working on this issue. You are not assigned to this issue. Without assigning , you draft a PR . Also in the issue of this PR there was a reference a open PR but you ignore that and open your PR . Please follow the rules and regulations of the organisation.
> 
> Next time no such things in review, this is opensource no one is forced here, you need to remove your this type of review from all the PR you have reviewed (if any) and yeah like I said earlier please review your review first, you haven't done that.

I am very sorry for that once again . I will remember this thing from next time

**Comment by Daronion** [comment]
Alright I will be waiting. Am I unable to start working on a low difficulty issue as long as this PR is open?

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2705/commits/db1298a20c862e4566f18ede6f93bc81912a788f

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2705/commits/c449f2725c220a3028373b776d17701b138ee3d3

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
