### PR TITLE
Upgrade memento_client to 0.6.1 #1968

### LINKED ISSUE #1968: Upgrade memento_client to 0.6.1
Currently `memento_client` in our repo is still at version 0.5.3 which still contains bugs. Upgrading to `0.6.1` would fix many bugs that are found in `0.5.3`

### PR DESCRIPTION
**Pull request by jw3126**
Fix #1968

### CODE REVIEW

**Comment by jw3126** [comment]
Any ideas, what the CI fails are about?

**Comment by IpshitaC** [comment]
The builds are failing because the requirements need to be updated in the `Gemfile` as well as `package.json`.
https://travis-ci.org/coala/coala-bears/jobs/262799941#L4049

**Comment by jw3126** [comment]
Thanks for the help. It is not clear what needs updating in the `Gemfile` / `package.json`.  I see nothing there that is obviously connected to my change? Also locally the tests pass. How to find out what to adjust?

**Comment by refeed** [comment]
@jw3126 Yeah like @IpshitaC says (https://travis-ci.org/coala/coala-bears/jobs/262799941#L4049 ). Our CI script generates the requirements list by going through all bears and diff-ing it with your changes. As it shows in https://travis-ci.org/coala/coala-bears/jobs/262799941#L4043 you need to change the `memento_client` version in  `bear-requirements.txt` also, because actually that's the important part

**Comment by jw3126** [comment]
Thanks for pointing this out! It seem weird though, that we have to keep track of the requirements in two different places manually `bear-requirements.txt` and in the `Bear.py`.

**Comment by Alexander-N** [comment]
Please update the last line in the commit message so that it references the correct issue. The number is correct, but it's the coala-bears repo.

**Comment by Nosferatul** [comment]
ack bf51acb

**Comment by Nosferatul** [comment]
please rebase @jw3126 and LGTM

**Comment by jw3126** [comment]
Thanks for the help! I think this is ready for merge now.

**Comment by Alexander-N** [comment]
ack cf4132a

**Comment by Makman2** [comment]
@rultor merge

**Comment by Makman2** [comment]
@jw3126 
> Thanks for pointing this out! It seem weird though, that we have to keep track of the requirements in two different places manually bear-requirements.txt and in the Bear.py.

This will change somewhen when is more mature and would support installing stuff and would allow to generate such lists (probably not so hard for Python requirements, but for package requirements this is a different story ;D).

**Pull request merged**
