### PR TITLE
Add MlintBear

### PR DESCRIPTION
**Pull request by li-boxuan**
Perform lint check on Matlab code.

Closes https://github.com/coala/coala-bears/issues/2352

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by li-boxuan** [comment]
I have some concerns here:

1. Users need to add mlint executable to PATH. For example, on a Mac with MATLAB_R2017a installed:

    > export PATH="/Applications/MATLAB_R2017a.app/bin/maci64:$PATH"

    I wonder where I should put this instruction?

2. I used ```lengthofline.m``` and ```lengthofline2.m``` as test files. They are copied from Matlab sample code (See MathWorks copyright on both files) .  Would it be a copyright issue?

**Comment by MacBox7** [comment]
@li-boxuan adding the executable to the environment path is a basic requirement for many linters, if one wishes to execute them using CLI. This could happen with most of the linters. The error message submitted by coala would simply be `executable not installed`. Modifying it just for this special case IMO is not necessary. 
As for the copyright issue is it necessary to use **MathWord** code? Can't you come up with some test cases of your own?

**Comment by li-boxuan** [comment]
@MacBox7 Thanks for comments!

> adding the executable to the environment path is a basic requirement for many linters

This case is special to me because it is not trivial to find the ```mlint``` executable. It is not documented on Matlab website (They don't even tell users that there is such an executable; they only say ```mlint``` is a function call in Matlab). I didn't know the existence of ```mlint``` executable until I saw https://github.com/Gimly/vscode-matlab/blob/master/README.md.

> Can't you come up with some test cases of your own?

Yes, sure. The reason I used official examples is that I found them pretty nice and this would be consistent with the example on https://www.mathworks.com/help/matlab/ref/mlint.html. I would write my own test cases if it's necessary (but may not be as good as official ones).

**Comment by jayvdb** [comment]
Looks like this wont be migrated until after GSoC.  Closing

**Pull request closed without merging**
