### PR TITLE
Update index.rst

### PR DESCRIPTION
**Pull request by soccer3056**
Test change in index.rst

### CODE REVIEW

**Comment by manu-chroma** [comment]
@soccer3056 It's a good idea to put the link to the issue URL in the commit message. 

Also, your commit message could be more descriptive in general. Have a look at the following: http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by sils** [comment]
@manu-chroma so many thanks for helping us reviewing! Please encourage others to do that as well, this is awesome! :+1:

**Comment by manu-chroma** [comment]
@sils Got inspired by your GUADEC talk :P

**Comment by manu-chroma** [comment]
By the way, I think this is just a test PR @soccer3056 was doing, looking by the changes he made. 
Don't think it's an actual PR.

**Comment by manu-chroma** [comment]
@sils this pr can be closed.

**Pull request closed without merging**
