### PR TITLE
swift: Add __init__.py

### PR DESCRIPTION
**Pull request by sils**
Fixes https://github.com/coala/coala-bears/issues/1048

### CODE REVIEW

**Comment by jayvdb** [comment]
ack 1c91275 46d0fdb

**Comment by Mixih** [comment]
Test failing with coverage error: `bears/generate_package.py       63      0     18      1    99%`
Also, rst2html yeilds a new error  on RELEASE_NOTES.rst:
`RELEASE_NOTES.rst:121: (ERROR/3) Unexpected indentation.`
Probably related....

**Comment by Mixih** [comment]
Update: This issue is currently in master. I'm opening an issue #1052.

**Comment by sils** [comment]
reack
fa4afa5 RELEASE_NOTES: Update for 0.9.1
475c7ba swift: Add __init__.py

**Comment by Mixih** [comment]
Hmmm, the coverage is failing in a weird place:
@128
````python
124    for bear_file_name in sorted(set(glob('bears/**/*Bear.py'))):
125        bear_object = next(iimport_objects(
126            bear_file_name, attributes='kind', local=True),
127            None)
128        if bear_object: <------- This line is yellow (is the false case not testing anymore?)
129            bear_name, _ = os.path.splitext(os.path.basename(bear_file_name))
130            create_file_structure_for_packages(
131                os.path.join('bears', 'upload'), bear_file_name, bear_name)
````
it really doesn't make sense. Why would this __init__.py break the generator?

**Comment by Mixih** [comment]
see issue #1055 for permanent solution.

**Comment by jayvdb** [comment]
Needs to be rebased on top of https://github.com/coala/coala-bears/pull/1056

**Comment by jayvdb** [comment]
ack cac6451 53d0d9d

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
