### PR TITLE
DuplicatefileBearTest.py: use assertEqual instead assertEquals

### PR DESCRIPTION
**Pull request by supriyanta**
fixes https://github.com/coala/coala-bears/issues/2050

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by nealkarpe** [comment]
Hi @supriyanta! The work you did looks good to me :smiley:. However, your PR failed on CircleCI tests as you didn't adhere to the [Commit Guidelines](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html). Capitalise the 'F' in "fixes" as `Fixes` is a keyword. Also, keep your shortlog short :wink: (must be under 50 chars). Instead, explain what your commit does in the body of the commit message! Try again good luck :smiley:

**Comment by prnvdixit** [comment]
@supriyanta Please, read the above review carefully and make requested changes 👍

**Comment by supriyanta** [comment]
Why circlecCi fails?

**Comment by prnvdixit** [comment]
@supriyanta Add a commit description too - It should tell the reasoning behind doing these changes (i.e. because the earlier one is set to be deprecated) 👍 😄
Also, use ```Closes <full_issue_url>``` in issue reference.

**Comment by supriyanta** [comment]
I think the problem is not in commit message,somewhere else.

**Comment by RaiVaibhav** [comment]
@supriyanta  Use `Closes` instead of  `Closes issues`

**Comment by RaiVaibhav** [comment]
@supriyanta  see `Circle CI` passes, did you get the difference here :wink:  , also please change your commit message make it to something like `assertEquals has been deprecated instead use assertEqual` so that everyone understands why these changes are made,  your commit message is still inappropriate

**Comment by supriyanta** [comment]
Yeah, thanks a lot!

**Comment by mridubhatnagar** [comment]
Hey @supriyanta.
Congrats on raising your PR in the community.
In my opinion we can amend the commit message a bit.

It changes the code
We can replace this and have something like

Use assertEqual as assertEquals has been
deprecated.

**Comment by supriyanta** [comment]
Okay

**Comment by mridubhatnagar** [comment]
@supriyanta Just pinged to check in case you are stuck somewhere.
To incorporate the change you'll just have to amend the commit message.
Using git commit --amend. And then force push. 

If you are facing any issues still. You can ping in the coala gitter channel.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
