### PR TITLE
MypyBear: Add ASCIINEMA_URL

### PR DESCRIPTION
**Pull request by sils**
I noticed it was missing when doing the tweet.

### CODE REVIEW

**Comment by nemaniarjun** [comment]
Seems okay

**Comment by adtac** [comment]
ack https://github.com/coala/coala-bears/pull/939/commits/56227360ee3f6b94b3c92e1282034c0cddaced07

**Comment by sils** [comment]
@rultor merge

**Comment by adtac** [comment]
that's a new error :D

**Comment by sils** [comment]
it's old - pypi gets unstable again

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
