### PR TITLE
Release 0.11: Reactive VintBear

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/coala/coala-bears/issues/1788

### CODE REVIEW

**Comment by meetmangukiya** [comment]
ack d7ab929

**Comment by meetmangukiya** [comment]
For 80d5bec

> vim-vint 0.3.11 is not compatible with requests 2.15+.
shouldn't commit message state 0.3.10 ?

**Comment by jayvdb** [comment]
> shouldn't commit message state 0.3.10 ?

No.  See issue.  It was 0.3.11 which was incompatible.

**Comment by jayvdb** [comment]
reack 80d5bec

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
