### PR TITLE
Upgrade DistributionRequirement

### PR DESCRIPTION
**Pull request by jayvdb**
Upgrades REQUIREMENTS for:

- CPPCheckBear
- CSecurityBear
- CSharpLintBear
- GNUIndentBear
- LicenseCheckBear
- LatexLintBear
- PerlCriticBear
- RubySyntaxBear
- VerilogLintBear
- XMLBear

Closes https://github.com/coala/coala-bears/issues/1659

### CODE REVIEW

**Comment by sils** [comment]
can you add a link to the related dependency management changes in the commit message? Think that'd be good

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1660/commits/b07b50b5c42115ade1a13680b101e082498a39f1

Though I haven't looked up every single package at the respective manager there doesn't seem to be spelling errors with those.

**Comment by sils** [comment]
ack b07b50b

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
