### PR TITLE
LanguageDefinition: Adapt to new coala API

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by jayvdb** [comment]
ack 8251edeae25
@rultor merge

**Comment by jayvdb** [comment]
@rultor stop

**Comment by sils** [comment]
ack 8251ede

**Comment by jayvdb** [comment]
@rulor merge
ack 76bb255

**Comment by sils** [comment]
ack 76bb255

**Comment by jayvdb** [comment]
@rultor merge

**Comment by aptrishu** [comment]
so after this change, IndentationBear doesn't work on python files.

**Pull request merged**
