### PR TITLE
ApertiumLintBear.py : Fixed Spelling Errors

### PR DESCRIPTION
**Pull request by prashantksharma**
Closes https://github.com/coala/coala-bears/issues/1966
### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

With reference to the issue https://github.com/coala/coala-bears/issues/1966.I have made the changes.And created PR to merge with my branch https://github.com/prashantksharma/coala-bears/tree/coala-prakush. Thanks to @stellargo  for tip.

### CODE REVIEW

**Comment by prashantksharma** [comment]
@stellargo , yes "Closes https://github.com/coala/coala-bears/issues/1966" is supposed to tell that corrected the issue.

**Comment by stellargo** [comment]
@gitmate-bot rebase

**Comment by stellargo** [comment]
@prashantksharma your short log is over 62 characters, you need to reduce it. Also go through commit guidelines :) First word should be the name of the file you have changed  and the body should contain specific details :)

**Comment by prashantksharma** [comment]
@stellargo reduced the short log to 43 chars.Please see if anything else is required.Thanks

**Comment by prnvdixit** [comment]
@prashantksharma It seems like your commit is missing a ```commit body``` (Giving a short description of the changes you have done - ```72``` chars per line).
Kindly, go through http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html once 😄 - That should be sufficient. :+1:

**Comment by Makman2** [comment]
> @stellargo reduced the short log to 43 chars.Please see if anything else is required.Thanks

Not the PR title ;)

**Comment by Makman2** [comment]
Btw: A commit body is not mandatory, but it usually helps if you provide additional info (except if it's really self-explaining)

**Comment by mridubhatnagar** [comment]
@prashantksharma For this PR to get merged in the coala code base. You need to change the commit message and follow a standard that everyone who are part of the community adheres too. So, basically 
it goes like this

Filename to which change is made: Few words regarding what change is about

Description of the change you have made to the files. In order to close the
issue.

Closes link to the issue it closes. 

So, in your commit description you are meant to add 

Changes consits to consists and inconsitency to 
inconsistency.

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
