### PR TITLE
change assertEquals to assertEqual, closes #2049

### LINKED ISSUE #2049: KeywordBearTest: Use `assertEqual` instead of `assertEquals`
Appears e.g. in https://circleci.com/gh/coala/coala-bears/7124?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link:
```
tests/general/KeywordBearTest.py::KeywordBearDiffTest::test_keyword_outside_of_comment
  /home/ubuntu/coala-bears/tests/general/KeywordBearTest.py:125: DeprecationWarning: Please use assertEqual instead.
    self.assertEquals(result[0].diffs, {})
```

### PR DESCRIPTION
**Pull request by urohit011**
Replaced assertEquals with assertEqual.

closes #2049 
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by stellargo** [comment]
gitmate-bot rebase

**Comment by Makman2** [comment]
Please format your commit message according to our guidelines ;)
```
<filename (without extension)>: <change summary>

<additional notes>

Closes <full-link-to-issue>
```
(Use `Closes` instead of `Fixes` as the referenced issue is not marked as bug)

**Comment by urohit011** [comment]
Got it, will make the necessary changes very shortly. :-)

**Comment by Makman2** [comment]
Nah not the PR title, but the commit message ;)
`git commit --amend`

**Comment by urohit011** [comment]
Made the changes to the commit message.

**Comment by Makman2** [comment]
1. "Closes" should start with upper-case
2. When we're already on it, you can add a period after "Use assertEqual instead of assertEquals" :)

Looks good otherwise :+1:

**Comment by urohit011** [comment]
Made the changes @Makman2.

**Comment by urohit011** [comment]
@stellargo  I took a look at a couple of merged pull requests and I did not see file extensions mentioned :-)  and @Makman2 has also mentioned that file extension is not required :-). About the master branch thing, do I have to make a new branch and send a oull request?

**Comment by Makman2** [comment]
ack 5d8fd18

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
> About the master branch thing, do I have to make a new branch and send a pull request?

No not now, but for the next PR ;)

**Comment by urohit011** [comment]
Will remember that @Makman2 .

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
