### PR TITLE
 .moban.yaml: Add CI check scripts

### PR DESCRIPTION
**Pull request by jayvdb**
Depends on https://github.com/coala/coala-bears/pull/2612

### CODE REVIEW

**Comment by sangamcse** [comment]
`TextLintBearTest` is failing on Python 3.6.

https://travis-ci.org/coala/coala-bears/jobs/404782492#L7735

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2614/commits/69be8327dc06bf23e9c084adfaeed62b1a992427

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2614/commits/abdb23a914e00a3b1cededcb737fb5f9a0b8f753

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
