### PR TITLE
.travis.yml: Add sentinel job

### PR DESCRIPTION
**Pull request by jayvdb**
This makes Python 3.6 the sentinel job,
so it runs by itself initially and causes
all other jobs to be cancelled if it fails.

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
c.f. https://github.com/coala/coala/pull/5542 for the main repo

**Comment by jayvdb** [comment]
Turns out that caching is working, but something is causing the R libraries to be rebuilt on Python 3.6.
Python3.6 https://travis-ci.org/coala/coala-bears/jobs/393940806
Python3.6 https://travis-ci.org/coala/coala-bears/jobs/394084183

Python3.4 https://travis-ci.org/coala/coala-bears/jobs/394084185

This change would make a bears build take twice as long to complete all of the jobs, which means close to 1.5 hrs for a full rebuild.
But we could make the Python 3.6 job a 'thin' python-only job (importing a bit of logic from https://github.com/coala/coala-bears/pull/1386)

**Comment by jayvdb** [comment]
Actually splitting the jobs by runtime makes the sentinel useless, as we can tell travis which job should go first.

**Comment by jayvdb** [comment]
Example: failure in 2.9 minutes

https://travis-ci.org/jayvdb/coala-bears/builds/400680800

**Comment by Makman2** [comment]
ack c8f29f49b1328848b1a8d3ba8f4e113eb1011c93 08d4ded9850c7e4030fba6374efefed231795ccf

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
