### PR TITLE
CI: Use cs50/ppa for astyle 3.0.1

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/coala/coala-bears/issues/2302
Related to https://github.com/coala/coala-bears/issues/2592

### CODE REVIEW

**Comment by harshhx17** [comment]
@jayvdb 
I am slightly confused as to how is astyle being downloaded for Circleci now? 
Or is it not needed by Circleci...

**Comment by jayvdb** [comment]
Read the circle log to check that is happening.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/commit/703f0dc862e989a59769b074b4d611ceb3c06177

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
