### PR TITLE
Fix uncached build breakages

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2239/commits/62a07467334bc013e28332857bfdb9ca75c52e16 https://github.com/coala/coala-bears/pull/2239/commits/f292ece68cfa8768a1d6ebbf0121066a68d121e1

**Comment by Makman2** [comment]
No reviews, self-acking as per maintainers decision.

**Comment by Makman2** [comment]
ack 5bb403924ae7735eb95fef08257e5e09fb7373a5 4c32c8b9920fa0d54ca3a731b33e66537789b5a4

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
