### PR TITLE
Use run to catch exceptions

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by jayvdb** [comment]
Would be good for https://github.com/coala/coala-bears/pull/1003/commits/25a763d6a9339ee commit message to say "Reverts https://github.com/coala/coala-bears/commit/53273c3f465a0e67abda73df1" , and/or mention to https://github.com/coala/coala-bears/pull/1003

**Comment by jayvdb** [comment]
ack 6444774ef23a1fd

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1003/commits/27456044fde8907d2adb212d657923377d8cdc69 thanks so much for this!

**Comment by Makman2** [comment]
reack 422a037

**Comment by jayvdb** [comment]
ack 009c0426184d66b9

**Comment by jayvdb** [comment]
ack 3a13849eb9684

**Pull request merged**
