### PR TITLE
deps.sh: Split into smaller files

### PR DESCRIPTION
**Pull request by jayvdb**
Splitting deps.sh allows the time to complete to be measured by
the CI systems, indicating where build times can be improved.

### CODE REVIEW

**Comment by jayvdb** [comment]
Note this includes a lot of https://github.com/coala/coala-bears/pull/1386 , and will help with https://github.com/coala/coala-bears/issues/1759

https://circleci.com/gh/jayvdb/coala-bears/718 is an uncached build.  If the now reduced deps.sh is still taking too long , we can split off other chucks of it into separate files, or add `time` if one of the remaining groups is a single command (e.g. node/ruby) - we can estimate some of these chunks by looking at the Docker builds which do use `time`.

**Comment by jayvdb** [comment]
The travis build errors are due to a problem while fetching the bash codecov

https://travis-ci.org/coala/coala-bears/jobs/236197564#L3841

https://github.com/coala/coala/issues/3718 is the solution for that problem.

**Comment by jayvdb** [comment]
Splitting it makes it easier to see problems like https://github.com/coala/coala-bears/pull/1777 , as `deps.sh` should now be very quick when cached.

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/1769/commits/b2d8fa97a89a99a04aabd8fb2b8da8adca8f46ea

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/1769/commits/b738960b47d4c21a2f5442f63d2de63a6f37e1f3

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
