### PR TITLE
PythonPackageInitBear.py: Create Asciinema

### PR DESCRIPTION
**Pull request by sibasish14**
Record an asciinema that shows the usage of PythonPackageInitBear.py

Closes https://github.com/coala/coala-bears/issues/1167

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Didn't get you @ayush1999 .
It seems it's already made from a forked repo. 
Branch - sibasish14:my_first_good_pull_request
And it's sibasish14/coala-bears and not coala/coala-bears.

**Comment by ayush1999** [comment]
@mridubhatnagar Yeah. But this isn't visible from FastHub( I hope they come up with another version for Android ).:) Apparently now everything's clear. PR looks good to me!

**Comment by mridubhatnagar** [comment]
Oh yes, that might be the reason. Through phone even I was not 
able to see it. Looks good.

**Comment by mridubhatnagar** [comment]
ack  12284d3

**Comment by sibasish14** [comment]
@ayush1999
Sir, all changes were made in my own fork and I followed the exact same steps mentioned in the guide.

**Comment by newbazz** [comment]
ack 12284d3ad9541ca23489e710c0653fc212ea7c8a

**Comment by ayush1999** [comment]
@sibasish14 Shorten the shortlog. Also, rebase your commits.

**Comment by sibasish14** [comment]
An unintentional commit. Sorry.

**Comment by sibasish14** [comment]
@ayush1999 is it ok now?

**Comment by sibasish14** [comment]
@newbazz can't do that. I, unfortunately, updated my current branch instead of my master branch.
So, git rebase -i  isn't showing any commits that I could squash!! It's showing completely empty except for the comment lines. Can you help??

**Comment by newbazz** [comment]
@sibasish14 i dont think they will merge it this way!!! what u can do is delete the branch from local and create a new one that is upto date with the master, and now make same changes and push ur commit ;)
P.S This is not good method but is still one alternative.

**Comment by sibasish14** [comment]
@newbazz will I be able to merge my previous commit if I do so?

**Comment by newbazz** [comment]
Yup ;)

**Comment by sibasish14** [comment]
@newbazz when I'm `git status `on my master branch, it's showing that it's 2 commits ahead(It was after I updated my master branch).
Is that normal?

**Comment by newbazz** [comment]
How did you updated your master branch? `git pull https://github.com/coala/coala-bears.git` or you made any changes in the master branch.

**Comment by sibasish14** [comment]
`git fetch upstream`
then switched to master branch
then `git merge upstream/master`
I didn't make any changes in the master branch

**Comment by newbazz** [comment]
okk thats great, than its normal now first do  `git push` to ur master branch.
Then `git checkout -b my_first_good_pull_request`
Make the required changes and push ur commits ;)

**Comment by sibasish14** [comment]
`git push` says everything up-to date.
Should I proceed by deleting my previous `my_first_good_pull_request` and creating a new `my_first_good_pull_request`

**Comment by newbazz** [comment]
Yup.

**Comment by sibasish14** [comment]
Should I delete the branch in my github repo as well??

**Comment by newbazz** [comment]
Nope, that will close the Pr.

**Comment by sibasish14** [comment]
oh ok then

**Comment by newbazz** [comment]
Than make a new brach with same name and make changes in that, and push ur commits,

**Comment by sibasish14** [comment]
Do I have to squash before push?
Or I'll push the recent one?

**Comment by newbazz** [comment]
No squash, just push

**Comment by sibasish14** [comment]
```
! [rejected]        my_first_good_pull_request -> my_first_good_pull_request (non-fast-forward)
error: failed to push some refs to 'https://github.com/sibasish14/coala-bears.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
```
this showed up while pushing

**Comment by newbazz** [comment]
Do git push -f

**Comment by sibasish14** [comment]
@newbazz I pushed it. Did anything happen? I can't see any differences except for that the checks have started again.

**Comment by newbazz** [comment]
Why is the number of commits still 2?

**Comment by sibasish14** [comment]
I was wondering the same.

**Comment by sibasish14** [comment]
What's the problem in merging 2 commits?
P.S. - Even when one of them is empty.

**Comment by ishanSrt** [comment]
unack https://github.com/coala/coala-bears/pull/2154/commits/538c998a0553c8358be4e52382289e139c90991e

**Comment by jayvdb** [comment]
@sibasish14 

> What's the problem in merging 2 commits?

We don't accept contributions from people who cant follow guidelines.
Either learn the ropes, or we close your PR and give your issue to someone else who is eager to learn.

**Comment by ShivamSinghania** [comment]
@sibasish14 And read newcomer guide again if needed.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
