### PR TITLE
CredoBear.py: Linter for elixir

### LINKED ISSUE #1266: Linter for elixier see https://github.com/rrrene/credo difficulty/low
Opened via [gitter](https://gitter.im/coala/coala/?at=586f85249d4cc4fc5381bb13) by @nemaniarjun

### PR DESCRIPTION
**Pull request by robinsjdotcom**
This bear lints elixir files using `credo`. 

Fixes #1266

### CODE REVIEW

**Comment by sils** [comment]
both of your commits do the same thing, the second commit is more of a "fixup commit" right? So they belong together :) can you squash them? (Google "git squash commits")

**Comment by sils** [comment]
secondly you add like a full blown project to the tests directory - is this reallyneeded!? That's a hell lot of stuff that we actually don't really care about, can we reduce this to a minimum? Take a look at other test cases. Real life exposureis important but the tests should each handle concise things

**Comment by robinsjdotcom** [comment]
@sils Yes, I was going to squash it before asking for a review and merge. My bad, I will remove the project generated dependencies. 

I was looking at other test cases, when developing those. Should I include more real-life test cases? 

Thanks 😄

**Comment by sils** [comment]
Hey @robinsjdotcom can you make a rebase? Might fix the tests, looks like a dep issue.

**Comment by robinsjdotcom** [comment]
Hi @sils going to fetch recent updates and rebase. Looks like travis-ci supports elixir/erlang by default,  will update the shell scripts and see if I get it working 😄 

Thanks!

**Comment by sils** [comment]
Why was this closed?

**Pull request closed without merging**
