### PR TITLE
README.rst: Add C to Supported Languages table

### PR DESCRIPTION
**Pull request by HarshaLaxman**
Added row at the top to contain C, and shifted to bottom row to fill in the top. Maintains alphabetical order. 

Closes https://github.com/coala-analyzer/coala-bears/issues/481

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, can you squash your commits together? Also the commit message needs a little work. More information is http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html - if you need anything more just ping me :)

**Comment by HarshaLaxman** [comment]
Sorry for the late reply I was trying to figure out how to squash the
commits for a while and then gave up, only remembering to come back today
:/. Looks like someone swooped it though

**Comment by underyx** [comment]
@HarshaLaxman I don't think so, there was a pull request opened for this 3 months ago, and yours was just mentioned on it yesterday. The issue is still yours to resolve :)

For squashing, we have a guide that will probably come in handy: http://coala.readthedocs.io/en/latest/Developers/Git_Basics.html#squashing-your-commits

You should also feel free to join our gitter.im chat if you need help with it.

**Comment by HarshaLaxman** [comment]
I couldn't figure out how to squash the commits so I just made a new pull request here: https://github.com/coala-analyzer/coala-bears/pull/797

**Comment by Adrianzatreanu** [comment]
closing as this was moved.

**Pull request closed without merging**
