### PR TITLE
Update LanguageToolBearTest.py

### PR DESCRIPTION
**Pull request by Hazen91**
Corrected grammar in german sentences.

### CODE REVIEW

**Comment by sils1297** [comment]
Hey, you're from germany? Where from? :)

You need to change your first commit instead of pushing new ones. [This page](http://coala.io/git) may help you to get started on this. (*Btw, do not press the update branch button. It's evil.*)

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala-bears.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

In the editor that opens you can squash commits together and do other awesome stuff!

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by sils1297** [comment]
Also, can you improve your commit  message? http://coala.io/commit should help you getting it right! (Don't change the PR title, change the *commit*, use `git commit --amend` to change the latest commit after the rebase thing.)

**Comment by Hazen91** [comment]
Hey, 
thanks for all the info and a big apology for the inconveniences! I'm new to Git.
Yes, I'm from Germany. Wilhelmshaven to be precise (North-West Germany).
I was just looking for some easy things I could help with to get the Hacktoberfest T-shirt x)

**Comment by sils1297** [comment]
Nice, I'm from hamburg :) Those newcomer issues are to get you started with git so nothing to apologize, it's like our "training program" :)

**Comment by sils** [comment]
@Hazen91 are you still on this?

**Comment by aptrishu** [comment]
@Hazen91  It's been a while we haven't seen an update from you. Would you mind let us know if you are going to fix this.

**Comment by sils** [comment]
closing due to inactivity, also lacking assignment

**Pull request closed without merging**
