### PR TITLE
PyUnusedCodeBear: Re-indent autoflake.fix_code

### PR DESCRIPTION
**Pull request by dosarudaniel**
Re-indent autoflake.fix_code invocation according to pep8,
after @sils sugestion.

Closes https://github.com/coala/coala-bears/issues/1015

### CODE REVIEW

**Comment by arjunsinghy96** [comment]
Do not tag anyone in your commit message.

**Comment by arjunsinghy96** [comment]
Everything else looks fine to me.

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/1023/commits/308e65c6d0486a0e7a5c322ff31cddc7973e8950

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
