### PR TITLE
Sils/pingbear

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/coala/coala-bears/pull/1032/commits/3a3870386096a873cb35d148371277934b5c4b8a

I'm too tired to check the regex, sorry :P

**Comment by sils** [comment]
hah shit:

```
requirements.txt
|   1| #•Use•>=•for•development•versions•so•that•source•builds•always•work
|    | [NORMAL] PinRequirementsBear:
|    | The minor version is missing.
```

@underyx that'll also affect your bear! It finds commented stuff...

**Comment by Mixih** [comment]
Starting review

**Comment by Mixih** [comment]
ack 7cb7f8e b4f161b

**Comment by sils** [comment]
reack
0898447 Deprecate coalib testing modules
5ba6dd2 Add PinRequirementsBear

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
