### PR TITLE
AnnotationBearTest.py: Remove an extra space

### PR DESCRIPTION
**Pull request by srk97**
Removed an unwanted space in the import statement that imports HiddenResult.

Closes https://github.com/coala/coala/issues/3153

### CODE REVIEW

**Comment by Nosferatul** [comment]
Try `Removed an unwanted space` instead of your commit body.

**Comment by jayvdb** [comment]
ack f4cb83c

**Comment by srk97** [comment]
@jayvdb  There's only one commit.

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
Needs a rebase.

**Comment by srk97** [comment]
@jayvdb  Is there something I need to do about this?

**Comment by jayvdb** [comment]
(Do not use the GitHub rebase button, as that creates additional unnecessary commits; do it manually)

**Comment by srk97** [comment]
@jayvdb Do I rebase it?

**Comment by jayvdb** [comment]
I've already answered that.

**Comment by srk97** [comment]
@jayvdb  Rebase done manually. Please check.

**Comment by jayvdb** [comment]
ack 2759cee

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
