### PR TITLE
GitCommitBear.py: Rename param in docstring

### LINKED ISSUE #571: GitCommitBear: Change ``returns`` to ``return``
[line](https://github.com/coala-analyzer/coala-bears/blob/master/bears/vcs/git/GitCommitBear.py#L147)
difficulty/newcomer

### PR DESCRIPTION
**Pull request by sahildua2305**
Change docstring to use 'return' instead of 'returns'.
Fixes #571

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Hi, you have a minor issue where there should be an empty newline above the "Fixes #bugno" line in the commit message.
I'm accepting it anyway as it's minor. If you can do it soon, fix it please.

ack 1c18d5d

**Comment by sahildua2305** [comment]
Done @AbdealiJK 👍

**Comment by Nosferatul** [comment]
ack 03b53b1

**Comment by AbdealiJK** [comment]
I've asked appveyor to rebuild.

**Comment by sils** [comment]
Hey,

we use some bug prediction in coala which relies on the `Fixes` keyword in commit messages. To get good results from that we need to use `Closes` for normal issues instead of `Fixes` which should only be used for real bugs. (See also [the commit message docs](http://coala.io/commit).)

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by sils** [comment]
unack 03b53b1

**Comment by sahildua2305** [comment]
Done, @sils

**Comment by adtac** [comment]
@sahildua2305 about the commit message - `return` is not really a param, is it? IMO a better commit mesasge would be a simple

    GitCommitBear.py: `returns` -> `return`

I know this is nitpicking, but these reviews really help you get started with coala development quickly, trust me :)

**Comment by Adrianzatreanu** [comment]
bump @adtac 's comment

**Comment by sahildua2305** [comment]
@adtac Seems like GitMate isn't happy with that commit message.

**Comment by adtac** [comment]
@sahildua2305 play around with the shortlog a bit ;)

**Comment by Adrianzatreanu** [comment]
Try:

``GitCommitBear.py: Change `returns` -> `return```

**Comment by Adrianzatreanu** [comment]
the regex requires a verb in imperative mood i think, thats why.

**Comment by Nosferatul** [comment]
@sahildua2305 needs a rebase

**Comment by sahildua2305** [comment]
@Nosferatul Why? I can't see any merge conflicts.

**Comment by Nosferatul** [comment]
Your commit branch is behind 2 commits

**Comment by Nosferatul** [comment]
Click on your branch for this pr and you will see it!

**Comment by Makman2** [comment]
ack cfe8e17d54b413d62c4eab1777ced8f0a3efe96b

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
