### PR TITLE
GoReturnsBearTest.py: Change variable alignment

### PR DESCRIPTION
**Pull request by dracarys09**
Ensures that 'good_file1' and 'good_file2' variables
are aligned properly in the same line.

Closes https://github.com/coala/coala-bears/issues/44

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1171/commits/037167603e7c2868c1e958f266dc9c9315371419

**Comment by sils** [comment]
didn't I see this PR around earlier?!

**Comment by dracarys09** [comment]
@sils In the previous PR I did changes in the master branch...that was not good so I created a new branch and took those changes and created a PR...It would be great if you can delete the previous PR 😄

**Comment by dracarys09** [comment]
@sils there were some problems during merging before so I created this PR

**Comment by dracarys09** [comment]
@sils I can't seem to figure out why circleci is failing can you help me out here ?

**Comment by sils** [comment]
Good question, CC @Adrianzatreanu who last did siomething with the reqs

**Comment by sils** [comment]
your commit was cherry picked into https://github.com/coala/coala-bears/pull/1173 and will be merged for you

**Pull request closed without merging**
