### PR TITLE
PyLintBear: Update pylint version

### PR DESCRIPTION
**Pull request by nvzard**
Modifying tests as per PyLint updates.

Closes https://github.com/coala/coala-bears/issues/2180

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by nvzard** [comment]
@Makman2 when I am running the tests locally using `PyLint 1.8.1` they are not failing, but CI build is failing :/ ?

**Comment by ishanSrt** [comment]
>when I am running the tests locally using PyLint 1.8.1 they are not failing, but AppVeyor build is failing :/ ?

first check your pylint version: `pylint --version`

**Comment by nvzard** [comment]
@ishanSrt thanks for your review. I know that I need to alter the tests according to PyLint 1.8.1 and I am trying to find a solution. I already did spend quite some time reading PyLint documentation and going through the changelogs. I had already made sure that my PyLint version is 1.8.1. 

The thing is tests are failing for AppVeryor, not for Travis CI and I've beed trying to figure out what went wrong since then. 
Thanks again, I'll try to dig deeper and find a solution soon :)

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
