### PR TITLE
.gitignore: Add .DS_Store

### PR DESCRIPTION
**Pull request by nvzard**
This update ensure that DS_Store will be ignored

Fixes https://github.com/coala/coala-bears/issues/2067

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by nvzard** [comment]
The issue was marked as open and not assigned to anyone so I solved it.

**Comment by RaiVaibhav** [comment]
@nvzard  but he is not assigned on this issue and also we have pinged him but he did't respond

**Comment by RaiVaibhav** [comment]
If travis run successfully it will approve it just ping me @nvzard

**Comment by nvzard** [comment]
Thanks for review @RaiVaibhav, The Travis CI build passed

**Comment by RaiVaibhav** [comment]
@nvzard  we have to wait for the person who has send PR for  certain time ,can you please try to focus on other newcomer issue till then

**Comment by Makman2** [comment]
But imo it's not okay if you copy someone's work and don't mention him as a co-author. Please mention @cristianossd in your work.

**Comment by Makman2** [comment]
unack 74851fa

**Comment by nvzard** [comment]
@prnvdixit thank you for reviewing my PR. I've pushed the desired changes. 
Thanks a lot @RaiVaibhav for explaining, I was confused about this as I referred to http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html guide and it was not explained there. Thanks for explaining. 

@prnvdixit  I'd be happy to work on another newcomer issue :)

**Comment by prnvdixit** [comment]
@nvzard Kindly don't work on another newcomer issue 😆
> Mostly newcomer issues are to introduce you to basic workflow and convention practices (which I am sure you have been introduced to in your first newcomer PR). Plus, finding a newcomer issue is tough - So, I will also recommend moving to higher difficulty issue and leave the newcomer issues for some actual newcomer 😛 👍

**Comment by nvzard** [comment]
Okie :p Is everything fine with this PR?

**Comment by nvzard** [comment]
and how can I do that? Is there any specific procedure?

**Comment by prnvdixit** [comment]
@nvzard Yeah.... Go for them 😉 👍

**Comment by nvzard** [comment]
Thanks for helping me with my first PR :)

**Comment by Makman2** [comment]
ack 6905edc

**Comment by nvzard** [comment]
@Makman2 is this ready for merge ?

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
