### PR TITLE
setup: Ignore lxml on avg installation

### PR DESCRIPTION
**Pull request by sils**
@NiklasMM if this is good to you you'll wanna add it to your cherry PR :)

### CODE REVIEW

**Comment by jayvdb** [comment]
This doesnt help the average user, as they use pip, and pip uses the whl's , and wheel's dont run `setup.py`.

https://github.com/coala/coala-bears/issues/1476 would provide one way to do this, effectively marking some bears as 'use at your own risk'.

And of course https://github.com/coala/coala-bears/issues/1000 will solve this properly. (But that is waiting on improvements to package_manager which nobody seems to wont to work on unless I crack the whip).

**Comment by sils** [comment]
> This doesnt help the average user

It does, right now coala can't be installed without installing lxml via distribution and it gets the user a pretty mad looking error which isn't easy to understand.

With this we just don't install it by default, similar situation as language-check back then.

-------

Another story:

I'm actually looking at dependency_manager/package_manager right now because the build is broken due to an issue there that we never found yet but once I enabled the super() check_prerequisites check for linter we got lots of more testcases.

On linux this worked totally fine but on windows we get exceptions from dependency manager.

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/1931/commits/125acf4bac3ba782b45187e87cabfa9700e389e7

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
