### PR TITLE
GCI: Update JSONFormatBear.py 

### PR DESCRIPTION
**Pull request by BrainBuzzer**
Added asciinema url.

### CODE REVIEW

**Comment by aptrishu** [comment]
Hi,

It seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading http://coala.io/commit !

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).

Cheers!

**Comment by BrainBuzzer** [comment]
Hi. I have changed the message. I hope that will be OK

**Comment by aptrishu** [comment]
Still needs modification.
You see there are 3 sections in a commit message.
1-> commit shortlog
2-> commit body
3-> Closes or Fixes issue note with issue reference (if it fixes an issue)

**Comment by jayvdb** [comment]
HI @brainbuzz, you have not done the step ["Create an issue"](https://github.com/coala/coala/wiki/Google-Code-In-Task-Advanced-asciinema#create-an-issue-in-coala-bears-repository).

Once you have done that, you need to amend your commit so that you can append "`Fixes <url>`" to your commit body.

**Comment by BrainBuzzer** [comment]
@jayvdb I have added an issue. Thank you for help. I hope that will do it.

**Comment by sils** [comment]
I like the asciinema per se, the commit message isn't fully to our standards yet: see coala.io/commits

`Closes issue #...` -> `Closes <full issue url>`

**Comment by jayvdb** [comment]
Not quite, but very close.
Please add a blank line before 'Closes ...', and check the required syntax for the `Closes ..` line in the Good Commits document.

**Comment by BrainBuzzer** [comment]
Completed 👍

**Comment by tulphoon** [comment]
ack 51d86af

**Comment by tulphoon** [comment]
@rultor merge

**Pull request merged**
