### PR TITLE
KotlinLintBear.py: Add ktlint

### PR DESCRIPTION
**Pull request by parimatrix**
Lints your Kotlin files. Check code for coding standards and
semantical problems.

Closes https://github.com/coala/coala-bears/issues/2152

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
@parimatrix some gitmate problem can be solved by `running coala` also there is a bear available to solve the  problem --
>Directory "bears/kotlin" does not contain init.py file

  `also create a test for bear` to get 100% coverage, `run pytest` to check your created test.
`coala document will help you in creating a test`

**Comment by parimatrix** [comment]
@RaiVaibhav Thanks ! Okay will have to learn about the test coverage and init.py thing. Also, I ran coala locally but it did not show me some errors which were shown by gitmate. But I think I have resolved all the other issues except test coverage. Right?

**Comment by RaiVaibhav** [comment]
Get a overview of coverage but read all about init and how to create a test of bear. No ,you have not solved init problem, take a look at gitmate bot comment, 
And when you create a test coverage problem will gets solved

**Comment by Makman2** [comment]
Closing due to inactivity.

**Pull request closed without merging**
