### PR TITLE
Makman2/x

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1007/commits/2e0b370df77aa6e6036db26b54afe9a3f50f7f46 https://github.com/coala/coala-bears/pull/1007/commits/7f060da341ff3b9f1ab3c5452316f16c0bcf6d71 https://github.com/coala/coala-bears/pull/1007/commits/4bbea878d9dfd14b438f560f8338dc79166d39e8

**Comment by sils** [comment]
@Makman2 rebase and merge

**Comment by Makman2** [comment]
reack 93d0ece, 0079970, 7f22554

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
