### PR TITLE
Add support for yapf>=0.21.0<0.27.0 and fix filename in .ci/generate_bear_metadata.py

### PR DESCRIPTION
**Pull request by areebbeigh**
Modify test_allow_multiline_lambdas to be
version specific.

Closes https://github.com/coala/coala-bears/issues/2873

Change "overrides" filename from
package-manager-requirements.yaml to pm-requirements.yaml

Fixes https://github.com/coala/coala-bears/issues/2936

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

### CODE REVIEW

**Comment by areebbeigh** [comment]
> Needs a rebase

Done.

**Comment by jayvdb** [comment]
Refetch master bear-requirements.yaml

Use `.ci/generate_bear_metadata.py` , and then run `moban`.

**Comment by areebbeigh** [comment]
> .ci/generate_bear_metadata.py

I'm running into:
```
Warning: Both package-manager-requirements.yaml and /home/areebbeigh/.cache/moban/repos/mobans/package-manager-requirements.yaml does not exist
```

and I suspect this is because running `ci/generate_bear_metadata.py` sets `overrides: package-manager-requirements.yaml` whereas it should be `overrides: pm-requirements.yaml`.

New issue? Although this is probably just a change in https://github.com/coala/coala-bears/blob/afb068b11a634b9f869f5385337628284a42bab3/.ci/generate_bear_metadata.py#L461

**Comment by jayvdb** [comment]
Yup; new issue.  That is a bug in my PR.

**Comment by jayvdb** [comment]
You can add the fix to this PR as a separate commit.

**Comment by areebbeigh** [comment]
> You can add the fix to this PR as a separate commit.

Done.

**Comment by jayvdb** [comment]
Sorry ; wrong button press.

@areebbeigh , this needs another rebase, but please also revise your commit messages to follow the coala commit guidelines.  specifically the first line should start with a filename of the most important file in the commit which is being modified (usually not a file which is generated).

**Comment by jayvdb** [comment]
I'm going to merge this despite it failing due to https://github.com/coala/coala-bears/issues/2937 , which I'll fix after this is merged

**Pull request merged**
