### PR TITLE
bear-requirements.txt: Add six~=1.11.0

### PR DESCRIPTION
**Pull request by abhishalya**
coala-bears has been throwing internal version
conflict due to six requirement. This works as
temporary fix and ensures that six is managed
manually.

Closes https://github.com/coala/coala-bears/issues/2885

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by abhishalya** [comment]
@Makman2 @jayvdb Can you please review :)

**Comment by abhishalya** [comment]
This works as a hotfix for the `six` version conflict. This was happening on Python3.4 because `jsonschema` dropped support for Python3.4 and which bumped the requirement to `six>=1.11.0` while everyone else had `six>=1.10.0`. I did some analysis [here](https://github.com/coala/coala-bears/issues/2885#issuecomment-476185966), and found that the best way to handle this would be to manually handle the six dependency. This also means that if the packages update their six dependency or the build start to break this will need change as per them.

I still think this not a good best approach of handling version conflicts, but the way pip works right now, its hard to find a good fix. If you have better approaches, mention them here. :smiley:

**Comment by Makman2** [comment]
Is it possible to add a comment there referring to the issue? If someone reads that a year later that change is still understandable^^ And we then might even remove it again if things have improved^^

**Comment by abhishalya** [comment]
Irrelevant now due to https://github.com/coala/coala-bears/pull/2910

**Pull request closed without merging**
