### PR TITLE
JavaPMDBear: Add Mac support

### PR DESCRIPTION
**Pull request by sils**
The binary differs. The very same change was already apploed to the
CPDBear but people often forget this one.

Fixes https://github.com/coala/coala-bears/issues/998

### CODE REVIEW

**Comment by nemaniarjun** [comment]
ack 53273c3

**Comment by sils** [comment]
ack 53273c3

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/999/commits/7f0a95245348a2eb1586262719aaa5b99cb6965e

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/999/commits/8b54ef30a69ffbe7d60a8055a2045c83a8b9db60

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
