### PR TITLE
RELEASE_NOTES.rst : fix a warning that was thrown.

### PR DESCRIPTION
**Pull request by arghyatiger**
This fixes the issue
of reduplication
in restructured text
documents

fixes https://github.com/coala/coala-bears/issues/1046

### CODE REVIEW

**Comment by nemaniarjun** [comment]
You have broken more than you have fixed. 
Try to start from scratch and make only required changes. 
Also remember to rebase before pushing and squash commits.
Read http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html
to fix the error in shortlog.
Dont ask people for review, theyll review when they get time. In the meantime you can review others' PR.

**Comment by nemaniarjun** [comment]
Ack 5768948

**Comment by sils** [comment]
how does the commit solve the issue? Can you explain in the commit message?

**Comment by Udayan12167** [comment]
unack https://github.com/coala/coala-bears/commit/5768948bd4bf969c896c63d148d4de7f29bd8494

**Comment by arghyatiger** [comment]
yes i updated the commit @sils

**Comment by aptrishu** [comment]
Your commit message says `Fixes` , It should use `Closes` .
wondering why ? see https://coala.io/commit

**Comment by arghyatiger** [comment]
@aptrishu  changed closes to fixes :)

**Comment by aptrishu** [comment]
change RELEASE_NOTES to RELEASE_NOTES.rst in commit shortlog.

**Comment by arghyatiger** [comment]
Changed RELEASE_NOTE to RELEASE_NOTE.rst @aptrishu

**Comment by aptrishu** [comment]
ack d5723ce

**Comment by aptrishu** [comment]
@rultor merge

**Comment by aptrishu** [comment]
unack d5723ce

**Comment by aptrishu** [comment]
rebase needed @arghyatiger

**Comment by arghyatiger** [comment]
rebased @aptrishu

**Comment by aptrishu** [comment]
@rultor merge

**Comment by aptrishu** [comment]
unack cbf6629

**Comment by aptrishu** [comment]
@arghyatiger seems you have not rebased properly.
please ask for invitation here https://gitter.im/coala/coala . and ask `cobot explain rebase` .

**Comment by aptrishu** [comment]
You are 1 commit behind and 1 commit ahead.
It should be 1 commit ahead only. (from coala:master)

**Comment by aptrishu** [comment]
ack 4e339af

**Comment by aptrishu** [comment]
@rultor merge

**Comment by aptrishu** [comment]
unack 4e339af

**Comment by aptrishu** [comment]
You are making changes on your master branch.
Please revert that to match it with upstream and start working on a new branch. (changes are small :stuck_out_tongue: so it shouldn't be a problem)

**Pull request closed without merging**
