### PR TITLE
GitCommitBear: Removed doubled word 'end end'

### PR DESCRIPTION
**Pull request by satya-vinay**
Removes "end" from double word "end end".

Closes https://github.com/coala/coala-bears/issues/2452

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x]  I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
Please follow the commit guidelines mentioned above.

**Comment by satya-vinay** [comment]
@jayvdb I followed the commit guidelines and edited the comment. Is it fine now?

**Comment by jayvdb** [comment]
No. See https://github.com/coala/coala-bears/pull/2454/commits

And http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#editing-commit-messages

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/pull/2454#issuecomment-385254340 still not done

**Comment by jayvdb** [comment]
Read http://coala.io/commit carefully.

**Comment by satya-vinay** [comment]
@jayvdb Please review the commit changes.

**Comment by jayvdb** [comment]
Your [commit message](https://github.com/coala/coala-bears/pull/2454/commits) is still nothing like the examples given on http://coala.io/commit.

You need to add a blank line, and then `Closes https://github.com/coala/coala-bears/issues/2452`

**Comment by jayvdb** [comment]
Stop editing this PR on GitHub.

Start reading the guidelines that we keep telling you about.

You need to edit your commit, using command line `git`.

If you dont fix it in the next 24 hrs, this PR will be rejected and given to someone else to do.

**Comment by satya-vinay** [comment]
@jayvdb Sorry for committing so many mistakes and thanks for your patience in reviewing my PR.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2454/commits/47767572ab58360ce5fc55ebba6d1f97d1f3a533

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
(just waiting for our bot to come back online.)

**Comment by jayvdb** [comment]
ack 4776757

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
