### PR TITLE
TextLintBearTest: Close test files properly

### PR DESCRIPTION
**Pull request by akspr7**
Closes: https://github.com/coala/coala-bears/issues/2048

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
As of now your commit message is

> TextLintBearTest: Close test files properly

So, based on community's good commit message guidelines. You will have to amend your
commit message a bit. And add one more line Closes link to issue it closes.

>  TextLintBearTest: Close test files properly

Closes https://github.com/coala/coala-bears/issues/2048

**Comment by akspr7** [comment]
Hi @mridubhatnagar, thanks for the info about branch. I'll take care of it in future. 
And i have already added the link of the issue it closes.
Thanks for having a look on my PR.

**Comment by mridubhatnagar** [comment]
You have added closes here on this page. But when I click on commits tab it shows this.

[
screenshot from 2017-11-26 11-05-05

**Comment by akspr7** [comment]
Sorry for this, i have created a new pull request which have all the specifications specified by you

**Comment by mridubhatnagar** [comment]
Hey, I did not tell you to create a new pull request. 
I asked you to amend your commit message. 
git commit -- amend. 
Don't create a new PR.

**Comment by akspr7** [comment]
Actually i did it, but then something went wrong and i needed to create new PR.

**Pull request closed without merging**
