### PR TITLE
KeywordBear.py: Change docstring to triple quotes

### PR DESCRIPTION
**Pull request by ajitluhach**
Closes https://github.com/coala/coala-bears/issues/1797

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by meetmangukiya** [comment]
ack 0568fb4

**Comment by meetmangukiya** [comment]
@ajitluhach rebase, and get the tests to pass?

**Comment by jayvdb** [comment]
Yes, rebase will fix the CircleCI problem.
But your commit message has a spelling mistake

**Comment by jayvdb** [comment]
unack 0568fb4

**Comment by ajitluhach** [comment]
@jayvdb @meetmangukiya there is this extra commit about merging master into keyword, I never performed it. Also it's not shown in git log. There was same issue with my previous pull request.

**Comment by jayvdb** [comment]
That is not how you rebase.  See our developer docs.

**Comment by ajitluhach** [comment]
I haven't performed rebase yet. @jayvdb

**Comment by Nosferatul** [comment]
@JohnMoutafis please rebase and LGTM

**Comment by Nosferatul** [comment]
ack cb3e5ff

**Comment by JohnMoutafis** [comment]
@Nosferatul Not my PR mate.

**Comment by yash-nisar** [comment]
Not sure if we want the indentation part in another commit.

**Comment by Makman2** [comment]
Yes, definitely a separate commit for the indentation thing.

**Comment by Makman2** [comment]
unack cb3e5ff

**Comment by Makman2** [comment]
Also you are not really "fixing" the docstring, it's already valid, you just change format to a preferred style.

**Comment by Makman2** [comment]
However, I've created a new issue for the indentation issue: https://github.com/coala/coala-bears/issues/2120

Please don't fix this in your PR unless you get assigned to it (which will likely not happen because you are already solving a newcomer issue)

**Comment by Makman2** [comment]
Cherry-picked and merged sadly without addressing the comments at https://github.com/coala/coala-bears/pull/1930

**Pull request closed without merging**
