### PR TITLE
requirements: Use compatability operator

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
ack d80866c37918003bc52b048bb314c5985dec6734

**Comment by Adrianzatreanu** [comment]
ack 0e44f87c85267d414f81f6b646c2e636d5b17287

**Comment by sils** [comment]
reack 4b646e4

**Comment by sils** [comment]
Blocked by #915

**Comment by underyx** [comment]
unack https://github.com/coala/coala-bears/pull/912/commits/325478d7fe25a5fd572de5c419ca3fef46537535

Typo in commit message, `compatability` -> `compatibility`

**Comment by sils** [comment]
well that was helpful...

**Comment by Asnelchristian** [comment]
still compatability in commit body

**Pull request closed without merging**
