### PR TITLE
Sils/tailorbackport

### PR DESCRIPTION
**Pull request by sils**

### CODE REVIEW

**Comment by jayvdb** [comment]
ack 2b03773 699c0cf 2b03773

**Comment by sils** [comment]
b97d35a Release 0.9.1
0082dbf RELEASE_NOTES: Update for 0.9.1
f958ddd RELEASE_NOTES.rst: Fix newline error
2b03773 swift: Add __init__.py
reack

**Comment by Mixih** [comment]
circle isn't going to pass until to backport the test fixes too.

**Comment by Mixih** [comment]
test fixes have been backported. This is ready for merge after rebase.

**Comment by sils** [comment]
Yeah, planned to do that somewhen today

**Comment by Mixih** [comment]
reack 
6b65a0 83d7b4 634bf1 9c20722

**Comment by Mixih** [comment]
@rultor merge

**Pull request merged**
