### PR TITLE
WIP:- Fix master

### PR DESCRIPTION
**Pull request by srisankethu**
Fixes https://github.com/coala/coala-bears/issues/852

### CODE REVIEW

**Comment by SanketDG** [comment]
Could you put the Lint changes in a different commit?

Also see [#852 (comment)](https://github.com/coala/coala-bears/issues/852#issuecomment-250952582)

**Comment by SanketDG** [comment]
@srisankethu This looks okay.

But the commits dont have tags, I suggest you go through http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

Also, doesn't hurt to explain why you did the change, in the commit body.

You still have the `Lint` changes in your second commit.

**Comment by srisankethu** [comment]
You asked to make Lint changes in my second commit right?

**Comment by srisankethu** [comment]
You asked to make Lint changes in my second commit right?

**Comment by sils1297** [comment]
ack https://github.com/coala/coala-bears/pull/854/commits/9625b214a9e4be3173d224a9a2fcd9bf58849ea2 https://github.com/coala/coala-bears/pull/854/commits/6667c4afcc27b80001e7d30125245ce3d2ca0cd1

**Comment by sils1297** [comment]
this is important and the commit messages are o.k., merging now

**Comment by sils1297** [comment]
@rultor merge

**Pull request merged**
