### PR TITLE
AppVeyor CI: Allow builds on forks

### PR DESCRIPTION
**Pull request by jayvdb**
Exclude only branch 'sils/*'.

Closes https://github.com/coala/coala-bears/issues/1285
Related to https://github.com/coala/coala/issues/3664

### CODE REVIEW

**Comment by Vamshi99** [comment]
ack 7ea53db

**Comment by jayvdb** [comment]
reack 33020b6

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack 6cb5815

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
