### PR TITLE
Fixed issue #2304

### PR DESCRIPTION
**Pull request by farberbrodsky**
GitCommitBearTest.py: Fix docstring typo

messgae --> message

Fixes https://github.com/coala/coala-bears/issues/2304

### CODE REVIEW

**Comment by farberbrodsky** [comment]
Sorry :( What's the problem with what I've done?

**Comment by Naveenaidu** [comment]
@farberbrodsky Please go through the "http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html" . There's a error in your commit message and hence the error :)

**Comment by farberbrodsky** [comment]
Sorry. Is my commit message ok now?

**Comment by Naveenaidu** [comment]
You have changed your `comment message` of the issue not the `commit message`. Use `git commit --amend`. That'll help you correct your commit message and then do a `force push`.

**Comment by Naveenaidu** [comment]
And please change `Closes` to `Fixes`. You should use `Closes` only when it adds a feature/enhancement.

**Comment by farberbrodsky** [comment]
I have already deleted my fork, can I still amend?

**Comment by Naveenaidu** [comment]
@farberbrodsky  Firstly please **don't** delete your forks. And Don't Work on the master of your forked repo ,**Always work on a branch** .You can't do a amend from the deleted fork. The proper approach would be to make a new fork and submit  a PR from it.

**Comment by farberbrodsky** [comment]
@Naveenaidu Sorry again. I will keep this in mind next time. I submitted the request again: https://github.com/coala/coala-bears/pull/2324

**Comment by Naveenaidu** [comment]
@farberbrodsky No worries. It happens :)

**Pull request closed without merging**
