### PR TITLE
Release 0.10: Backport PR 1555: RuboCopBear.py: Pin to version 0.47.1

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by jayvdb** [comment]
There are strange errors on [my Travis build](https://travis-ci.org/jayvdb/coala-bears/builds/223812436), which I suspect are due to caching.

**Comment by jayvdb** [comment]
Note all these three commits are needed, or I need to disable the `.ci/generate_bear_requirements.py` script in CI,  which catches the bear requirements being out of sync with requirments.txt, Gemfile and package.json.

**Comment by yash-nisar** [comment]
ack 6a5a6beccb2293109e5c32d31a87e4b9143b13d4 482aef741d692beb8cd78f961a79f40a0b48b99b d690ec88d5ccb460a0f5742fb4c862fc3024f6fb

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
