### PR TITLE
.coafile: Enable reSTLintBear on README.rst

### PR DESCRIPTION
**Pull request by jayvdb**
Updates ineffective 47f61cc7

Closes https://github.com/coala/coala-bears/issues/1177

### CODE REVIEW

**Comment by Mixih** [comment]
ack da4eb3e

**Comment by Mixih** [comment]
now how the hell did that slip me 😓?

**Comment by jayvdb** [comment]
Raised https://github.com/coala/coala/issues/3372 about the slippage.

**Comment by jayvdb** [comment]
reack 03e881c

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
