### PR TITLE
#2050 tests/general/DuplicatefileBearTest.py

### PR DESCRIPTION
**Pull request by supriyanta**
used 'assertEqual' instead of 'assertEquals'

### CODE REVIEW

**Comment by RaiVaibhav** [comment]
unack 1197113b7b27cf02994cfdd09ab17775bb766b37

**Comment by RaiVaibhav** [comment]
Make sure you `force push` after changes

**Comment by supriyanta** [comment]
Okay

**Comment by RaiVaibhav** [comment]
Squash you commit  use `DuplicatefileBearTest.py: Use assertEqual` as your commit head

**Comment by sims1253** [comment]
you should take a look at http://api.coala.io/en/latest/Developers/Git_Basics.html#rebasing and clean up your commits.
Do an interactive rebase and squash them all into one. If you need help with this after reading the guide, ask for help in the chat.

**Comment by RaiVaibhav** [comment]
@supriyanta  need to know why this PR is still open when you have already created a new PR reagarding same issue

**Comment by jayvdb** [comment]
Duplicate of https://github.com/coala/coala-bears/pull/2262

**Pull request closed without merging**
