### PR TITLE
bear-requirements.txt: Omit inherited dependencies

### PR DESCRIPTION
**Pull request by jayvdb**
List inherited packages in requirements.txt, and
update generate_bear_requirements to not repeat
those packages in bear-requirements.

Use this to avoid adding requests to bear requirements.txt
Also fix requirement in InvalidLinkBear to match
requests version used by coala.

### CODE REVIEW

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/1348/commits/78e021bc280f14700903b90586b8cd7940b06699

**Comment by SanketDG** [comment]
Rebase needed.

**Comment by jayvdb** [comment]
reack df01777

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
