### PR TITLE
ClangFunctionDifferenceBear.py: Changes in docstrings

### PR DESCRIPTION
**Pull request by ayush1999**
Changes single inverted commas (') to double
inverted commas(") for the docstrings.

Closes: https://github.com/coala/coala-bears/issues/1999

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
lgtm ack 54f3fed

**Comment by palash25** [comment]
This looks good should be merged.
@ayush1999 a word of advice please don't open multiple PRs for one issue, this helps us keep the PR history clutter-free.

**Comment by prnvdixit** [comment]
unack 54f3fed99ac20d952bb31e5ddb9da5f90fc427cd

**Comment by RaiVaibhav** [comment]
@prnvdixit IMO its a request change not a but a bug, but it have to `change` not `changes`, correct me if i am missing some thing :)

**Comment by prnvdixit** [comment]
Feel free to reack it back 😃 - Though I am referring to this part in Shotlorg guidelines - ```Should describe the change - the action being done in the commit.```

**Comment by prnvdixit** [comment]
@palash25 It's exact 50 chars actually :wink:

**Comment by palash25** [comment]
@prnvdixit my bad I didn't notice that. Well I guess the author ought to edit his shortlog now.

**Comment by palash25** [comment]
@ayush1999  change your shortlog to the one that @prnvdixit suggested and then I will reack this.

**Comment by prnvdixit** [comment]
reack 5de6f277537112eec906f6416b663b930af4f254

**Comment by shreyans800755** [comment]
ack 5de6f27

**Comment by ayush1999** [comment]
@Makman2  I think this can be merged now. :+1:

**Comment by Makman2** [comment]
Please don't put a colon between `Closes` and the issue number, just `Closes XXXX`.

**Comment by Makman2** [comment]
unack 5de6f27

**Comment by ayush1999** [comment]
@Makman2 Done. :)

**Comment by palash25** [comment]
reack 5de6f27

**Comment by prnvdixit** [comment]
ack f69148829ec113249500b66884f48b6d1d3f389d
@palash25 That is "ack"ing wrong commit :joy:

**Comment by palash25** [comment]
@prnvdixit I didn't realise that. Good catch.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
