### PR TITLE
XMLBear.py: Add severity to XMLBear

### PR DESCRIPTION
**Pull request by yukiisbored**
This commit adds severity which are provided from the underlying
linter's output.

Fixes https://github.com/coala/coala-bears/issues/1099

### CODE REVIEW

**Comment by jayvdb** [comment]
> The issue is also about changing the priority of the style down to INFO.

Oh, that part is already done.  My apologies.
So we just need tests confirming the severities are correct.

**Comment by yukiisbored** [comment]
It looks like `xmllint` installation failed for Appveyor
```
RuntimeError: The bear XMLBear does not fulfill all requirements. 'xmllint' is not installed
```

**Comment by yukiisbored** [comment]
My bad, I forgot to add a skip decorator for it.

**Comment by jayvdb** [comment]
circle-ci seems to be having trouble. :/

**Comment by jayvdb** [comment]
ack 220edfb

**Comment by yukiisbored** [comment]
Closed due to circleci acting weird.
https://gitter.im/coala/coala?at=584936dc28d755bf14dcb5f4

**Comment by Mixih** [comment]
All reviews on hold because of circle acting up... Please be patient as they try fix their issuse :)

**Comment by sils** [comment]
Fixes -> Closes because of bug prediction

**Comment by Mixih** [comment]
In commit end, make fixes -> closes. wip because that

**Comment by sils** [comment]
otherwise good (could be split up but we don't wanne be *so* nitpicky  ;))

**Comment by jayvdb** [comment]
ack ac753d4

**Comment by sils** [comment]
cherry picked to https://github.com/coala/coala-bears/pull/1114, this will be merged for you. (Circle problems :/)

**Pull request closed without merging**
