### PR TITLE
KeywordBear.py: Change doctstring to triple quotes

### PR DESCRIPTION
**Pull request by ajitluhach**
Closes https://github.com/coala/coala-bears/issues/1797

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by rhemon** [comment]
not sure why travis or codecov failed, but you will need to rebase, so you may rebase and update this

**Comment by ajitluhach** [comment]
Looking into right now

**Comment by mridubhatnagar** [comment]
There are 2 commits already. You will have to squash your commits for this PR to merge into master.
For squashing your commits you can follow the guidelines present in http://api.coala.io/en/latest/Developers/Git_Basics.html document.

Still, if you are unable are facing issues with squashing you can ping in the gitter channel and members will help you out https://gitter.im/coala/coala.

**Comment by ajitluhach** [comment]
@mridubhatnagar I squashed the redundant commit about merging, does it look Okay now?

**Comment by mridubhatnagar** [comment]
Not yet. If you open the commits tab it shows 4 commits. There should only be 1 commit and not 4. You should pick only the valid commit and squash all the remaining commits.

**Comment by ajitluhach** [comment]
Oh, okay, I think I got it now, @mridubhatnagar

**Comment by ajitluhach** [comment]
@mridubhatnagar So I squashed all the commits after my original commit, but this one commit about merging persists to be there, although it isn't shown "git log"

**Comment by mridubhatnagar** [comment]
Provided you are on the current branch. You can do 

```
git reset HEAD^ --hard
```
This will remove your most recent commit. That is the merge commit. And HEAD will point to the valid commit.

**Comment by mridubhatnagar** [comment]
Hey, can you please reopen this issue. Closing issues is not the solution. This could have been resolved. Did you try doing the command I mentioned?

**Pull request closed without merging**
