### PR TITLE
Add CI space consistency check

### LINKED ISSUE #806: There's no check for trailing spaces in .ci/deps.sh
There also are some trailing spaces in there. :D

### PR DESCRIPTION
**Pull request by sazarkin**
My attempt to fix #806

### CODE REVIEW

**Comment by sils1297** [comment]
ack f779436

@jayvdb thank you so much for helping us reviewing. Just so you know: this (and all your other help) is highly appreciated!

**Comment by sils1297** [comment]
ack f779436

**Comment by sils1297** [comment]
Hey @sazarkin the build failures are not your problem - someting is generally wrong right now and we can't merge until it gets fixed.

@underyx do you hve an idea on what's wrong with the builds? Everything's on fire, would you have the time to help us out? :/

**Comment by sils1297** [comment]
ack https://github.com/coala/coala-bears/pull/848/commits/ffd08a2a3bcf1a2477ff14e97a31bcb81e2de3a4

**Comment by sils1297** [comment]
Hi,

it looks like your PR is out of date and needs a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*) The rebase should fix the builds!

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala-analyzer/coala.git
```

(Be sure to use coala-bears on the coala-bears repository :))

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by sazarkin** [comment]
Done

**Comment by sils1297** [comment]
reack https://github.com/sazarkin/coala-bears/commit/714ae6fecc38338a6933b4cb039e28bb3eb9a80a

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

You can help us a lot by filling out <http://coala.io/newform>!

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Pull request merged**
