### PR TITLE
AppveyorCI: Use pip caching

### PR DESCRIPTION
**Pull request by jayvdb**
Replaces five pip commands performing custom caching
with one command which uses pip's inbuilt caching.

### CODE REVIEW

**Comment by Mixih** [comment]
ack a6def29

**Comment by Mixih** [comment]
ack 7bbbae4

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack ec789ab

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack ec789ab

**Pull request merged**
