### PR TITLE
PHPCodeSnifferBear: Double backticks around True

### PR DESCRIPTION
**Pull request by adtac**

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/90e9199b79bf159554e7769596bb6320a495a070

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
reack https://github.com/coala/coala-bears/pull/984/commits/02a96cc576a483d79fe4317a11b64651d72b7ab6

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
reack https://github.com/coala/coala-bears/pull/984/commits/46dd51a598e3263baf2c61e073dabeee833bcde6

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/1f8600b06457d596d13ec476b9190b65a5bf0ded

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/5b1e20cff879f988588d8b8ce33ccfcd99ee72af https://github.com/coala/coala-bears/pull/984/commits/463ad2652369bf25b49b25f929d9372500e1f2d6

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/5b1e20cff879f988588d8b8ce33ccfcd99ee72af https://github.com/coala/coala-bears/pull/984/commits/463ad2652369bf25b49b25f929d9372500e1f2d6

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by adtac** [comment]
reack https://github.com/coala/coala-bears/pull/984/commits/3c50e2168b8cf4678635f8c5aac9f2c9d037d62e https://github.com/coala/coala-bears/pull/984/commits/5fd3e7ab26723bdc0a99f96bad9e0495230d2fe1

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/80a1d34814b9e98ec908ca517d320eff1308fd10

**Comment by adtac** [comment]
@rultor merge

**Comment by adtac** [comment]
@rultor merge

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/b297d8f8e1ebb695cae4e2c34c17b79de22336cb

**Comment by adtac** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/5fd3e7ab26723bdc0a99f96bad9e0495230d2fe1

**Comment by adtac** [comment]
@rultor merge

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/984/commits/fcbccaf7c2d15621d65ab72bed46ad477d75b64e

**Comment by sils** [comment]
@adtac had to merge manually

**Pull request merged**
