### PR TITLE
Makes python formatting bears better configurable

### PR DESCRIPTION
**Pull request by kriti21**
Closes https://github.com/coala/coala-bears/issues/620

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by kriti21** [comment]
Please review @Makman2

**Comment by Makman2** [comment]
This issue is about implementing a bear-feature to automatically check for those code-style-problems :) Manually fixing is too easy (and humans tend to forget it ;) )

**Comment by Makman2** [comment]
unack 1cfbc234436b7f6fa4d99e2ad5971cf0d76e8856

**Comment by kriti21** [comment]
Oh okay :+1: How about implementing a generic bear to solve code style issues for all the python bears? Is this a good idea? @Makman2

**Comment by Makman2** [comment]
If you can integrate the feature into an existing bear, do it inside an existing bear. If it doesn't really fit, write a generic bear :+1:

**Comment by jayvdb** [comment]
Not useful to change style unless there is a rule which enforces it.

**Pull request closed without merging**
