### PR TITLE
PyUnusedCodeBear.py: Re-indent autoflake.fix_code invocation

### PR DESCRIPTION
**Pull request by dosarudaniel**
Closes https://github.com/coala/coala-bears/issues/1015

### CODE REVIEW

**Comment by tulphoon** [comment]
Looks good to me :)

**Comment by tulphoon** [comment]
ack 33f1ac3

**Comment by Makman2** [comment]
is this actually PEP8? shouldn't be those lines just 4 spaces indented?

**Comment by sils** [comment]
no, the indentation here is wrong. It should either be:

```python
asdasdasd(
    asd, asd,
    asd)
```

or aligned with the opening paren

**Comment by sils** [comment]
unack 33f1ac3

**Comment by dosarudaniel** [comment]
I will try again.

**Comment by arjunsinghy96** [comment]
Edit you commit message as directed by gitmate. Also see coala.io/commits

**Pull request closed without merging**
