### PR TITLE
PHPCodeSnifferBear: Add PSR-1 standard

### PR DESCRIPTION
**Pull request by Asnelchristian**

### CODE REVIEW

**Comment by sils** [comment]
what's PSR 1 and why do our users want it always?

**Comment by sils** [comment]
do all the settings we have still work as intended @Asnelchristian ?

**Comment by Asnelchristian** [comment]
yes

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/938/commits/2d8e20e54d2f7da170c50d76fab49473f2e10800

**Comment by sils** [comment]
ack 2d8e20e

**Comment by Asnelchristian** [comment]
yes

**Comment by Asnelchristian** [comment]
yes

**Comment by Asnelchristian** [comment]
reack https://github.com/coala/coala-bears/pull/938/commits/1e0469bda81a7139705ab36deff3c8a773dda566

**Comment by Asnelchristian** [comment]
@rultor merge

**Pull request merged**
