### PR TITLE
Fix builds on Ubuntu precise images

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by sils1297** [comment]
@oreqizer can you take a look at https://github.com/coala/coala-bears/pull/871/commits/a9840e37842b7bf53740f3b03919d14ab71335b5 ?

**Comment by oreqizer** [comment]
IMO it's a better idea to upgrade eslint plugins rather than downgrade eslint

**Comment by jayvdb** [comment]
I have limited knowledge of nodejs, but .. afaics, these are the latest supported versions, and even the dev accepted version as not eslist 3.

https://www.npmjs.com/package/eslint-config-happiness = 5.3.1
https://www.npmjs.com/package/eslint-config-happiness-jsx = 1.2.1

https://github.com/wesleytodd/eslint-config-happiness/releases
https://github.com/wesleytodd/eslint-config-happiness-jsx/releases

https://github.com/wesleytodd/eslint-config-happiness/blob/master/package.json#L14
`devDependencies: {"eslint": "^2.9.0"}`
https://github.com/wesleytodd/eslint-config-happiness-jsx/blob/master/package.json#L18
`devDependencies: {"eslint": "^2.1.0"}`

**Comment by Adrianzatreanu** [comment]
ack 8df0ea829386f55dc0a5704e8201a74ca1818e30

**Comment by sils1297** [comment]
ack https://github.com/coala/coala-bears/pull/871/commits/3397018e9e1435d87ac3b53c607c6847dfcd9734

**Comment by sils1297** [comment]
I talked with @oreqizer and we can downgrade eslint for now. He may find the time to reupgrade it properly soon - we should definitely do this.

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@stevepeak I had to disable codecov, there is an upload at https://codecov.io/github/jayvdb/coala-bears/commit/3397018e9e1435d87ac3b53c607c6847dfcd9734 but it still didn't report the state. This is causing too many problems lately :/

**Comment by stevepeak** [comment]
@sils1297 "didn't report the state" I'm seeing the commit posted. [Top of the logs here](https://codecov.io/gh/jayvdb/coala-bears/commit/3397018e9e1435d87ac3b53c607c6847dfcd9734/builds). What am I missing here?

**Comment by sils1297** [comment]
I think it's registered at the fork and not at the original.

**Comment by stevepeak** [comment]
@sils1297 This is what the CircleCI build stated as the testing slug. Is this indended? I'm confused because if that is the case then Circle would set the status on the fork repo not the original.

**Comment by sils1297** [comment]
@jayvdb has an own circle build, I have no idea why circle builds it in his namespace (and actually that sucks) but that's what it seems to do

**Comment by stevepeak** [comment]
This is the first instance I've heard of this issue... We can manually override the slug `-r coala/coala-bears -t repo-token` would fix it.

**Pull request merged**
