### PR TITLE
RuboCopBear : Upgrade to version 0.51.0

### PR DESCRIPTION
**Pull request by IpshitaC**
Closes https://github.com/coala/coala-bears/issues/2116

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by IpshitaC** [comment]
Hey @jayvdb Could you please take a look? :smile:

**Comment by jayvdb** [comment]
Ping when the build is green ;-)

**Comment by RaiVaibhav** [comment]
I think may be we have to add in documentation that `Turn off the trigger of CI on fork before submitting any PR to main repo` it causing problem.

**Comment by jayvdb** [comment]
No it doesnt cause a problem to have a build occur on the fork

**Comment by RaiVaibhav** [comment]
:+1: 
Then maybe my back to back changes in my fork causes this problem https://travis-ci.org/RaiVaibhav/coala-bears/jobs/299595097

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2118/commits/131fafaf2c229757c2bd78d77e005a5da769bc91

**Comment by jayvdb** [comment]
@rultor merge

**Comment by RaiVaibhav** [comment]
@IpshitaC All changes is totally :+1:  but I think  have to add `Fixes the Travis CI problem` or something like that  because if some read then don't understand why this commit made here

**Pull request merged**
