### PR TITLE
moban: Sync from moban templates

### PR DESCRIPTION
**Pull request by frextrite**
Sync all the good changes from coala/mobans repository

Mobans job will still continue failing until coala/mobans is synced back

Closes https://github.com/coala/coala-bears/issues/2853

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
The changes to `.ci/check_setuptools.py` look like they are sync-able, and important.

And please rebase.

**Comment by frextrite** [comment]
> The changes to `.ci/check_setuptools.py` look like they are sync-able, and important.

I'm not getting you here. imo `check_setuptools.py` doesn't have any template in mobans so how can I sync it?

**Comment by jayvdb** [comment]
https://github.com/coala/coala-bears/blob/master/.moban.yaml#L46

**Comment by frextrite** [comment]
> https://github.com/coala/coala-bears/blob/master/.moban.yaml#L46

This line basically copies `check_setuptools.py` from `../coala-mobans/assets/ci` to `.ci/`. And the only difference between the two is the blank line present in one and not the other. However, since we are copying file from one location to another and not syncing the file(no template exists), this would not cause any problem with the mobans job.

**Comment by jayvdb** [comment]
> ... this would not cause any problem with the mobans job.

but the file is still out of sync.  This PR is about doing a sync.  Please sync everything which can be sync'd, so the next sync's dont have to be concerned with this file.

**Comment by jayvdb** [comment]
Ah ... it was my copy of mobans which was out of sync.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2865/commits/7118dfe565904afa9a9981ea4dc51fb7c37ffa59

**Comment by jayvdb** [comment]
ack 7118dfe

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
