### PR TITLE
LogPrinter: Replace LogPrinter with logging

### PR DESCRIPTION
**Pull request by shreyans800755**
Closes https://github.com/coala/coala-bears/issues/1948

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by shreyans800755** [comment]
Ref https://github.com/coala/coala/issues/4484

**Comment by yash-nisar** [comment]
@shreyans800755 Rebase and your tests shall pass :wink:

**Comment by shreyans800755** [comment]
@yash-nisar
I'm expecting this to fail. I'm waiting for https://github.com/coala/coala/pull/4608 to get merged first. After that, tests will pass as I'm not passing `log_printer` arg to one of the function. You can review that meanwhile.

**Comment by adhikasp** [comment]
This could be continued?

**Comment by nemaniarjun** [comment]
@shreyans800755 Are you still on this? Or should I close this? :)

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/1949/commits/9b4ce09e4309fae0106ed1d9dae6400bb75cf732

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
