### PR TITLE
GitCommitBear.py: Change regex to shortlog_regex

### PR DESCRIPTION
**Pull request by etotientz**
Closes https://github.com/coala/coala-bears/issues/1217

### CODE REVIEW

**Comment by dracarys09** [comment]
ack https://github.com/coala/coala-bears/pull/1399/commits/af54c5a4ed85a41ddbb0fe2d01c5cef6168ce594

**Comment by sims1253** [comment]
@etotientz you have already fixed a newcomer issue. Please only do one as they mainly exist to teach newcomers.

**Comment by sims1253** [comment]
closing this for the same reason as the other one. Also you were not assigned to both issues and the guide states you should never work on issues without assignment.
Please follow the guide to avoid these problems in the future.

**Comment by etotientz** [comment]
ok,my mistake.I got it.

**Pull request closed without merging**
