### PR TITLE
KeywordBearTest.py: Named arguments replaced with named keywords

### PR DESCRIPTION
**Pull request by SiddharthKumar02**
Closes https://github.com/coala/coala-bears/issues/1314

### CODE REVIEW

**Comment by ankit01ojha** [comment]
@SiddharthKumar02 I think you should use `KeywordBearTest.py: Replace  arguments  with keywords`

**Comment by Asnelchristian** [comment]
your commit short seems to be too long,  :sweat_smile:

**Comment by Asnelchristian** [comment]
This is good, and it is clear that you have read the guide :+1:  :heart:

**Comment by Asnelchristian** [comment]
just some few modifications and it is good to go

**Comment by Techievena** [comment]
Well @SiddharthKumar02 it was my mistake of giving wrong heading to the issue. Therefore I had asked to replace the term `Named keywords` to `Named arguments` in the issue heading. This has got nothing to do with your PR. Your head may be something like `KeywordBearTest.py`: Assign name to the arguments` or something like that.

**Comment by namanyadav12** [comment]
ack 417352e

**Comment by SiddharthKumar02** [comment]
Thanks to all of you for your help :)

**Comment by Makman2** [comment]
@SiddharthKumar02 you have to rebase, then we can merge :+1:

**Comment by SiddharthKumar02** [comment]
@Makman2 I rebased it.

**Comment by Makman2** [comment]
@SiddharthKumar02 sorry I just merged something else, you have to rebase again ;)

**Comment by SiddharthKumar02** [comment]
@Makman2  Haha, That's alright. It's good practice for me :)

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1317/commits/a70176dcab8ad0e4c4c6880ff8fc2c5b9db6f32f

**Comment by SiddharthKumar02** [comment]
@Makman2 Rebase done.

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
