### PR TITLE
AnnotationBear.py: Corrects typo in docstring

### PR DESCRIPTION
**Pull request by CatalinFetoiu**
Changes the four occurences of contatining into containing, in
the docstring of function find_annotation_ranges.

Fixes https://github.com/coala/coala-bears/issues/1293

### CODE REVIEW

**Comment by Mixih** [comment]
Changes is ok int he body, we only need imperative int he commit shortlog(first line of coomit)

**Comment by CatalinFetoiu** [comment]
Ok, I changed it :)

**Comment by aptrishu** [comment]
ack 1892b64722

**Comment by Makman2** [comment]
@rultor merge

**Pull request merged**
