### PR TITLE
.gitignore: Adds .vscode/

### PR DESCRIPTION
**Pull request by Anubhav-Bhargava**
This adds .vscode to gitignore. 
Now it'll ignore vscode files

Fixes https://github.com/coala/coala-bears/issues/2394

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
unack https://github.com/coala/coala-bears/commit/ff6bad32e1b5c831eb84e3be1369796adc7eff28

**Comment by palash25** [comment]
@aps120797 I see that you haven't even joined coala.

If you want to contribute to coala we welcome you. But at least read our guides and join the organization and get to know the community before blindly approving any changes and that too when a maintainer has already unacked the commit before your approval.

Btw if you are interested in contributing please check out http://api.coala.io/en/latest/Developers/Newcomers_Guide.html

**Comment by palash25** [comment]
ping @Anubhav-Bhargava please read the commit guidelines http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html your commit message doesn't follow them.

Also I think it would be best if you drop the description and only keep the shortlog and the issue link.

> The commit message says adds .vscode, this should also indicate that .vscode is a directory.

@ksdme I don't think that there is a file named `.vscode` so I'm not sure how that would cause confusing its always a directory.

**Comment by jayvdb** [comment]
Also this should have been Closes , not Fixes, as this is not a bug.

Closing due to inactivity.

**Pull request closed without merging**
