### PR TITLE
YapfBear.py: Reduce if-condition

### PR DESCRIPTION
**Pull request by ragnerok**
if-condition was simplified as in #928
Fixes https://github.com/coala/coala-bears/issues/928

### CODE REVIEW

**Comment by Makman2** [comment]
@ragnerok you sure the referenced issue is addressed with that commit? I think it's about something else^^ Could you maybe ask @jayvdb again what he exactly means?

**Comment by Nosferatul** [comment]
Also please do not refer to an issue 2 times `Fixes: #928` is fine

**Comment by Nosferatul** [comment]
Also you have 2 PRs for the same issue. please close one of them

**Comment by jayvdb** [comment]
@ragnerok , I already told you that this patch wasn't sufficient to solve the problem, and 15 mins later you submit this Pull Request with the same patch.  If you need clarification, please discuss this at https://github.com/coala/coala-bears/issues/928 .

**Pull request closed without merging**
