### PR TITLE
Fix German (+ English) sample in LanguageToolBearTest

### PR DESCRIPTION
**Pull request by kerstin**
Fix for #25.
Also fixes grammar error in original English sentence.

### CODE REVIEW

**Comment by kerstin** [comment]
Err... don't merge this PR, I guess?
Reason: it doesn't follow your commit message scheme.

See also my comments in #25.

**Comment by Nosferatul** [comment]
That's right. @kerstin Please follow https://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html. Thx for your contribution!

**Comment by aptrishu** [comment]
@kerstin It doesn't seem like you are assigned to https://github.com/coala/coala-bears/issues/25 . Please get assigned first to work on an issue, just to avoid duplicate PRs.
and Yes, Please follow the commit guideline.

**Comment by kerstin** [comment]
@aptrishu No, I was not assigned and I argued why I still made the PR in #25. I then also explained why I won't touch the issue anymore until at least November – but I can certainly step back altogether. 

You repeating to me once again that I should follow the commit guidelines was unnecessary though seeing as I noted this myself (in here) and @Nosferatul also already mentioned it.

**Comment by aptrishu** [comment]
The main motto of the comment was to make sure that assigned people submit the PR though anyone can make the PR. Good to see your contribution eagerness. All this was just to avoid duplicate PRs. Happy coding. :)

**Comment by jayvdb** [comment]
@kerstin , the content of your patch looks good.
Can you revise your commit message using `git commit --amend`  and then `git push -f`.

**Comment by kerstin** [comment]
@jayvdb Will do!

**Comment by kerstin** [comment]
Btw. not sure if you consider this a fix of a bug or an enhancement. A grammatically incorrect sentence is certainly buggy but maybe fixes are only reserved for programming bugs.

**Comment by kerstin** [comment]
Hmmmm. Ok, not sure what went wrong there. Will investigate.

**Comment by jayvdb** [comment]
Ya, "Closes" is better IMO. This isnt a user-facing bug.

gitmate is complaining about the shortlog.

`.coafile` has
```
shortlog_regex = ([^:]*|[^:]+: [A-Z0-9*].*)
```

**Comment by kerstin** [comment]
Ahh, indeed, I used a lower case letter after the colon, thanks for the regex. (If I read it correctly, it doesn't allow any special characters either? The examples in the tutorial do use punctuation marks though.)

Fixing now.

**Comment by kerstin** [comment]
Wait, I missed that `.*` at the end of the regex! Makes sense now. (:

**Comment by Nosferatul** [comment]
Also, please rebase!

**Comment by kerstin** [comment]
I did?

**Comment by Nosferatul** [comment]
I know, it happens to all of us 😄

**Comment by kerstin** [comment]
What would I do to check if this might have happened? Do another fetch immediately after (then rebase again if necessary)?

**Comment by Nosferatul** [comment]
Yes, or you could check on your pr to see if the branch is out-of-date( n commits behind master )

**Comment by kerstin** [comment]
@Nosferatul Where in my PR would I see that?

**Comment by Nosferatul** [comment]
Where tests are showed. In the right side of `This pull request can be automatically merged by project collaborators` you will see a button `Update branch` if that button it's active that means you should rebase!

**Comment by Nosferatul** [comment]
ack d955dc2

**Comment by Nosferatul** [comment]
@rultor merge

**Comment by kerstin** [comment]
@Nosferatul Hm, I didn't see such a button (just checked in other PRs too), maybe it's only visible to maintainers? I'll just do the fetch thing in the future. Thanks for the help in any case!

**Comment by sils** [comment]
hey, in case you didn't already, can you help us by very quickly filling
https://coala.io/newform ?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Comment by Nosferatul** [comment]
It's there for sure, that's the way i checked if I need a rebase. Anytime 😄

**Comment by sils** [comment]
but you have a higher access level nosferatul, maybe it's not visible for
everyone. You can see it on github on the fork "is .. commits behind" ..!=0
-> rebase

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

On 29 October 2016 at 15:41, Alexandru-Sorin Maxim <notifications@github.com

**Comment by Nosferatul** [comment]
I forgot to mention that's the way I checked before having a higher access level

**Pull request merged**
