### PR TITLE
Support git-url-parse version 1.2

### PR DESCRIPTION
**Pull request by Naveenaidu**
The git-url-parse version has been updated
to support 1.2 and also to allow the
support for all future 1.x

Closes https://github.com/coala/coala-bears/issues/2869

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
Waiting for the new version on opensuse repo as requested on issue

**Comment by Naveenaidu** [comment]
@jayvdb 
[Package created](https://build.opensuse.org/package/show/home:Naveenaidu:branches:devel:languages:python/python-git-url-parse) and [Submitted](https://build.opensuse.org/package/requests/devel:languages:python/python-git-url-parse)

**Comment by jayvdb** [comment]
You removed the first entry in .changes, and didnt include a list of changes that occurred in the latest release.

**Comment by jayvdb** [comment]
Fix submitted https://build.opensuse.org/request/show/674359

**Comment by Naveenaidu** [comment]
> You removed the first entry in .changes, and didnt include a list of changes that occurred in the latest release.

Opps!! :see_no_evil: , Sorry about that. It was my first time to send a new package and I missed to keep the detail in mind. Thanks for the fix :)

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2872/commits/ef08b6cb6b9f4eddefbc150a62225068295b4e02

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
