### PR TITLE
HTMLLintBear: Upgrade `html-linter`

### LINKED ISSUE #2004: HTMLLintBear: Upgrade `html-linter` to 0.4.0
difficulty/newcomer

### PR DESCRIPTION
**Pull request by sangamcse**
HTMLLintBear.py: Update to `html-linter 0.4.0`
from version `html-linter 0.3.0`.
This commit also changes to `html-linter 0.4.0` version in `bear-requirements.txt`.

Closes https://github.com/coala/coala-bears/issues/2004

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
@sangamcse Have a look at the commit guidelines. 
You will have to add Closes link-to-the-issue-it-closes. In your commit message. 
If mention Closes and reference the issue link with it. In order to make reviewing of the task easy.

**Comment by sangamcse** [comment]
@mridubhatnagar It has the link. I've given `Closes https://github.com/coala/coala-bears/issues/2004` and after submitting my message, it converted it into `Closes #2004`.

**Comment by mridubhatnagar** [comment]
That I am aware of. But I cannot see it in commit message. 
screenshot from 2017-12-03 13-18-50

**Comment by newbazz** [comment]
That is what u have commented @sangamcse

**Comment by sangamcse** [comment]
@newbazz @yash-nisar It looks like there is some problem but I'm not getting it. I tried to give my best.

**Comment by sangamcse** [comment]
Done @mridubhatnagar @newbazz @yash-nisar.

**Comment by sangamcse** [comment]
@yash-nisar I've re-pushed it. Let's see what ci result is coming.

**Comment by mridubhatnagar** [comment]
ack 87c5ae9

**Comment by yash-nisar** [comment]
Looks good to me !

**Comment by yash-nisar** [comment]
@aptrishu The PR looks good to me, please merge it if looks good to you too 👍

**Comment by aptrishu** [comment]
@sangamcse rebase and its good to go.

**Comment by sangamcse** [comment]
@aptrishu as I haven't done it before, can you help me rebasing it? The PR was sent using origin/htmllint branch.

**Comment by mridubhatnagar** [comment]
@sangamcse  Read this it has steps for rebasing http://api.coala.io/en/latest/Developers/Git_Basics.html.

**Comment by sangamcse** [comment]
@mridubhatnagar @yash-nisar I think I did something wrong while rebasing as you can see above. It shows I've re-pushed my PR.

**Comment by mridubhatnagar** [comment]
I think it is rebased. In the docs it is mentioned how you can verify if rebase is done or not. 
When I checked web page of the branch in your fork. It does not show n commits behind.
It just says 1 commit ahead. And that is because of your current commit.

**Comment by sangamcse** [comment]
@mridubhatnagar Thanks! It is rebased.

**Comment by mridubhatnagar** [comment]
ack 8c5931f

**Comment by Makman2** [comment]
unack 8c5931f

**Comment by Makman2** [comment]
Commit message:
> HTMLLintBear.py: Upgrade~~s~~ `html-linter`

Just remove the 3rd person "s", we use imperative tense ;)
(I wonder why our CI checks + coala didn't catch that again...)

**Comment by Makman2** [comment]
But otherwise good to go :+1:

**Comment by sangamcse** [comment]
@Makman2, removed "s". But now gitmate-bot has problem with that. Please review it.

**Comment by Makman2** [comment]
Huh :O that's bad, that looks like a bug...

**Comment by Makman2** [comment]
ack 4267204

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by yash-nisar** [comment]
@gitmate-bot rebase

**Comment by yash-nisar** [comment]
@Makman2 Can you merge this patch when you get some time?

**Comment by Makman2** [comment]
Yeah sorry I forgot it again 😅

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
Forgot that gitmate is still disabled. Thus created a new PR where I can rebase manually: https://github.com/coala/coala-bears/pull/2196

**Pull request closed without merging**
