### PR TITLE
GitCommitBear: Change 'returns' to 'return'

### PR DESCRIPTION
**Pull request by MichalCab**
Closes https://github.com/coala-analyzer/coala/issues/269

### CODE REVIEW

**Comment by sims1253** [comment]
The fix looks good but your commit message needs a touch up. Please take a look at our guidelines and add/change what is needed:
 http://coala.readthedocs.io/en/latest/Developers/Writing_Good_Commits.html

Thank you for the contribution!

By the way, to edit the last commit, use git commit --amend, edit it, save it, and then push again with the extra flag --force :)

**Comment by sims1253** [comment]
Could you add the fixes part into the commit message? then it is fine :)

**Comment by MichalCab** [comment]
@sims1253 Thanks for link, added :)

**Comment by sims1253** [comment]
For a small change like that this is totally alright. Just as an example how it could look if this would be a more complex change:

GitCommitBear.py: Rename param in docstring

Change the docstring to use 'return'

Fixes coala-analyzer#571

**Comment by sims1253** [comment]
ack c71c88c

**Comment by sims1253** [comment]
I just learned that we use Closes for typos and not Fixes :)
could you change that?

**Comment by sims1253** [comment]
unack c71c88c

**Comment by Adrianzatreanu** [comment]
hey could you change your commit message as @sims1253 mentioned? something like, but with full link to the issue at the Closes

GitCommitBear.py: Rename param in docstring

Change the docstring to use 'return'.

Closes coala-analyzer#571

**Comment by Adrianzatreanu** [comment]
closing due to long inactivity.

**Pull request closed without merging**
