### PR TITLE
LocalBearTestHelper.py: Remove unused imports

### PR DESCRIPTION
**Pull request by CormacGG**
removed unused import
"from coala.coalib.testing.LocalBearTestHelper.py import *"

closes https://github.com/coala/coala-bears/issues/1057

### CODE REVIEW

**Comment by aptrishu** [comment]
Tests are failing. marking it wip.

**Comment by Mixih** [comment]
Bad idea.... You just removed the entire functionality of this module... You may have to look in coals for the fix...

**Comment by CormacGG** [comment]
What does it mean by "Unused import 'collections'"

**Comment by Nosferatul** [comment]
You can look where are imports declared. Search on google how import looks.

**Comment by CormacGG** [comment]
How do i submit a new pull request?

**Comment by Nosferatul** [comment]
@CormacGG Why do you want another one? You need a rebase, drop on gitter and use `cobot explain rebase`

**Comment by CormacGG** [comment]
Hey, a bit embarrassing but, I made a mistake and had to delete my local repository and now I don't know how I'm going to update this commit/pull request. Any help would be appreciated

**Comment by Mixih** [comment]
Re -clone your repo... That's the beauty of git. Github should still have your repo in it's servers. Follow the newcomer's guide again, just omit the make your fork step ;)

**Comment by CormacGG** [comment]
I mean, I deleted it from the GitHub website, and re cloned your guys'

**Comment by CormacGG** [comment]
Hey I added a change, if it doesn't work, can you explain what is meant by import "collections".

**Comment by Nosferatul** [comment]
Yes, this is my mistake, the file was changed and the import isn't there anymore. I'll suggest another newcomer issue if you want it as soon as I find something. Sorry for the trouble again.

**Comment by CormacGG** [comment]
Yes I'd love that :) thanks

**Comment by Nosferatul** [comment]
Closing it because of the import isn't there anymore.

**Comment by Nosferatul** [comment]
@CormacGG  I assigned you, check the issue, I hope it's ok now!

**Pull request closed without merging**
