### PR TITLE
Added asciinema demonstrating how to use yapfbear

### LINKED ISSUE #895: YapfBear: Make asciinema
@Mariatta  are you interested?

### PR DESCRIPTION
**Pull request by Mariatta**
Closes #895 

Please check it out and let me know if this works 😸 
This is the first asciinema that I made 🎉 
Thanks!

### CODE REVIEW

**Comment by Asnelchristian** [comment]
awesome :+1:

**Comment by Asnelchristian** [comment]
Well you have to modify your commit short log a little as said in http://docs.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog. Maybe 
'YapfBear: Add ASCINEMA URL' :sweat_smile:

**Comment by Asnelchristian** [comment]
you might wanna try a difficulty/low issue after this one is merged :)

**Comment by Mariatta** [comment]
Thanks @Asnelchristian I think I updated the shortlog message.
Please check :)

**Comment by Mariatta** [comment]
I'm interested to take on this one next https://github.com/coala/documentation/issues/99 What do you think? :)

**Comment by Asnelchristian** [comment]
oops ( you have to add what issue your commit `Fixes` or `Closes` in the commit message body )

**Comment by Mariatta** [comment]
ok will try to fix this again hold on

**Comment by Mariatta** [comment]
Is this ok now?

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/900/commits/811830a337cd442708ccccf21d82cd0bdc2c9de7

**Comment by Asnelchristian** [comment]
it is :), Congratulation your first PR.... :+1: Awesome

**Comment by Mariatta** [comment]
Yay! 🎉🎉 Thanks so much!

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by sils** [comment]
Hey,

can you fill coala.io/newform ?

Sincerely,

Lasse Schuirmann

lasse@schuirmann.net
http://coala.io/ - http://viperdev.io/ - http://gitmate.com/

**Pull request merged**
