### PR TITLE
RELEASE_NOTES.rst: Update URL references

### PR DESCRIPTION
**Pull request by Vamshi99**
Changing 'coala-analyzer' to 'coala'

Closes https://github.com/coala/coala-bears/issues/1382

### CODE REVIEW

**Comment by naveentata** [comment]
ack d210f87

**Comment by supergr35** [comment]
unack d210f87

**Comment by supergr35** [comment]
Please change your commit shortlog to use "Change" instead of "Changing". This uses the imperative tense. See the following link :)
http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html#shortlog

**Comment by Vamshi99** [comment]
@supergr35 , Is it okay now?

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1387/commits/77fba9279646bbe423c4061c9cc29423ef28c3a0

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
