### PR TITLE
FilenameBear.py: Add kebabcase naming convention

### PR DESCRIPTION
**Pull request by yash-nisar**
Closes https://github.com/coala/coala-bears/issues/1533

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by yash-nisar** [comment]
The `snake-with-hyphen` naming convention is called as the `kebab case`. I have opened this PR so as to continue with https://github.com/coala/coala-bears/issues/1083. @jayvdb

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/1535/commits/76274da34f10e15d158584acd23164b31dfd732b

**Comment by yash-nisar** [comment]
Yaayayy @Asnelchristian , we can quickly merge this once the tests pass so I can continue with https://github.com/coala/coala-bears/issues/1083. Thanks a lot ! :D

**Comment by Asnelchristian** [comment]
ack https://github.com/coala/coala-bears/pull/1535/commits/b8c17ed95f665c7e8c2153b13098f55d6c227f43

**Comment by Asnelchristian** [comment]
@rultor merge

**Comment by NiklasMM** [comment]
@rultor merge

**Pull request merged**
