### PR TITLE
Add YAMLLintBear in .coafile

### PR DESCRIPTION
**Pull request by kbhagi**
When running coala over a code add YAMLLintBear at .coafile to fix any style issues raised  by coala
Fixes https://github.com/coala/bear-docs/issues/39

### CODE REVIEW

**Comment by RJ722** [comment]
@mind-warrior I think you haven't added any file for the commit

You may go through http://api.coala.io/en/latest/Developers/Git_Basics.html#adding-the-files-and-commiting

**Comment by Monal5031** [comment]
@mind-warrior This PR is not valid in this repo, as .coafile already has `YAMLLintBear`. Please close this PR.

**Comment by mind-warrior** [comment]
Closing PR as told by Monal5031

**Comment by Monal5031** [comment]
@mind-warrior You have to close this PR not add another commit to it.

**Comment by Asnelchristian** [comment]
would you squash all those commits into one

**Comment by Asnelchristian** [comment]
```
git rebase -i HEAD~(number of commits)

change pick->squash to merge a commit to the previous one
```

**Comment by jayvdb** [comment]
This task has already been completed, and the PR doesnt contain changes any more, and the fork has been deleted.

**Pull request closed without merging**
