### PR TITLE
requirements.txt: Add click 6.6

### PR DESCRIPTION
**Pull request by sils**
coala builds are currently failing. This is a hotfix. We should revert
this when https://github.com/willkg/dennis/issues/91 gets resolved or
alternatively remove DennisBear.

### CODE REVIEW

**Comment by adtac** [comment]
ack https://github.com/coala/coala-bears/pull/1282/commits/291871bf4c0927774e27315ed65ddd81a3ac853e

**Comment by NiklasMM** [comment]
ack 291871b

**Comment by NiklasMM** [comment]
Looks good. Should we open a blocked issue to remove it again?

**Comment by adtac** [comment]
ack https://github.com/coala/coala-bears/pull/1282/commits/f0e8955b541dc60107dadd0f05fae18091b4a634

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
