### PR TITLE
Makman2/move diff from clang fixit

### PR DESCRIPTION
**Pull request by Makman2**

### CODE REVIEW

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
I still can't believe I'm causing the issue... retrying again with a rebase.

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
And blocked by https://github.com/coala/coala-bears/pull/2239

**Comment by Makman2** [comment]
No reviews, self-acking as per maintainers decision.

**Comment by Makman2** [comment]
ack 5be54f5 6e46ce0 af2b88b 52b2409

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
