### PR TITLE
Use ContextManagers.py from coala_utils

### PR DESCRIPTION
**Pull request by tulphoon**
ContextManagers.py from coalib has been removed
using coala_utils one instead.

### CODE REVIEW

**Comment by Mixih** [comment]
ack 5f8b02

**Comment by Mixih** [comment]
reack 583db1

**Comment by tulphoon** [comment]
@rultor merge

**Comment by aptrishu** [comment]
ack 583db11

**Comment by aptrishu** [comment]
@rultor merge

**Comment by Mixih** [comment]
ack dd77e3

**Comment by tulphoon** [comment]
@rultor merge

**Pull request merged**
