### PR TITLE
Cherry pick 2017 07 15

### PR DESCRIPTION
**Pull request by NiklasMM**
Cherry-picked a couple of approved PRs:

https://github.com/coala/coala-bears/pull/1761
https://github.com/coala/coala-bears/pull/1852
https://github.com/coala/coala-bears/pull/1925
https://github.com/coala/coala-bears/pull/1756
https://github.com/coala/coala-bears/pull/1887

### CODE REVIEW

**Comment by jayvdb** [comment]
This PR is already out of date.  Needs to be rebased :P 
This also defeats the point of the newcomer process, where they ideally learn about rebasing, and communicating.

**Comment by jayvdb** [comment]
Please rebase before adding more to this PR.  Every time you add a commit to this PR, you cause more builds to fire of.  And they cant be merged because they need to be rebased.

**Comment by NiklasMM** [comment]
> This also defeats the point of the newcomer process, where they ideally learn about rebasing, and communicating.

Fair point... I was getting frustrated with constant rebasing.

**Comment by jayvdb** [comment]
#1887 is now also merged, so you can remove that one.

#1925 is wrong.  Please remove it.

etc.

This rush to get stuff merged doesnt have good results.

**Comment by sils** [comment]
reack 34d2010020e31c2474b6de4f0d25ee982f862456 5455928827e1c6daecfdebe81df15325bbf2cb08 33745194778e9a9d09ca93a6e992d06b6931049f  06d1636f601a4d727fc0481edd7feef87b155d89

**Comment by sils** [comment]
@rultor merge

**Comment by Makman2** [comment]
Although very late, I just see: 06d1636
This commit was definitely not acked on its original PR at https://github.com/coala/coala-bears/pull/1861 and incorporates two issues at once without mentioning it. I know very late, but anyway, I hope this post is read and next time care is taken :+1:

**Pull request merged**
