### PR TITLE
Python minimum version 3.4.4

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/coala/coala-bears/issues/2611
Closes https://github.com/coala/coala-bears/issues/2488

### CODE REVIEW

**Comment by jayvdb** [comment]
Demo of the py27 and py33 jobs: https://travis-ci.org/jayvdb/coala-bears/builds/404723796
That is commit https://github.com/jayvdb/coala-bears/commit/8229d58daed714a88bcddd8df50426c2c881f994 which has parent 807b53784e90e, same commit as this PR.

**Comment by jayvdb** [comment]
The GitMate PR error is because of the revert commit, https://github.com/coala/coala-bears/pull/2612/commits/44012a9efd811baec611d80bc5ec4ca8c5be2b46 , which goes over the length limit because https://github.com/coala/coala-bears/pull/2241 hasnt been finished.

**Comment by jayvdb** [comment]
Demo https://travis-ci.org/jayvdb/coala-bears/builds/404768441 
is commit https://github.com/jayvdb/coala-bears/commit/3728c6d670faa9745d2145f015d9252ad36c2889 with parent https://github.com/jayvdb/coala-bears/commit/ace719b5781873196a82a0783bd0fd64198aa4ec which is the same as this PR

**Comment by jayvdb** [comment]
Verified at https://travis-ci.org/jayvdb/coala-bears/builds/416160340

**Comment by jayvdb** [comment]
Fresh verification build https://travis-ci.org/jayvdb/coala-bears/builds/416374555

To verify yourself, cherry-pick the following and run on a fork
```diff
diff --git a/.travis.yml b/.travis.yml
index c3e4fb4..80b0b6c 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -24,7 +24,7 @@ stages:
   - test
   - moban
   - name: unsupported
-    if: branch = master AND type = push
+    if: type != pull_request
 
 .check_moban: &check_moban
   <<: *disable_global
```

**Comment by ksdme** [comment]
LGTM.

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2612/commits/5ed8b8c728b3c637d6f981aee235483065514bf3 https://github.com/coala/coala-bears/pull/2612/commits/5379f4e7efdfcf48ff753ae846616fbc93c3594c https://github.com/coala/coala-bears/pull/2612/commits/aa6088586eaab55ec5ce26127fa99ca0490d806b https://github.com/coala/coala-bears/pull/2612/commits/d07dde473d8959b7dc062ca5005a714a02a237dd

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
