### PR TITLE
DuplicatefileBearTest.py: Renamed to DuplicateFileBearTest.py

### PR DESCRIPTION
**Pull request by gokberksahin**

### CODE REVIEW

**Comment by IpshitaC** [comment]
Hi @gokberksahin, congratulations on solving this issue! :tada: 
I see that this issue is not assigned to you. You can get yourself assigned to this issue. Just follow this [guide](https://api.coala.io/en/latest/Developers/Newcomers_Guide.html). You need to join the [coala gitter chat](https://gitter.im/coala/coala), type `Hello World` to get yourself invited to the community. Then request `corobo` to assign this issue to you.

Also, please refer to the [Writing Good Commits](http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html) guide and follow the commit guidelines that we prefer. :smile:

**Comment by yashovardhanagrawal** [comment]
Don't unnecessarily close the PR.
I think you are to git, and you need to learn it a bit
refer to the commit guidelines as told by @IpshitaC 

great that you have got the issue assigned to yourself

learn some git tricks from here http://api.coala.io/en/latest/Developers/Git_Basics.html

rebase your commit, add a proper message and description, and change the PR name & description also

**Comment by yashovardhanagrawal** [comment]
A better commit message (shortlog) can be 
`DuplicatefileBearTest.py: Rename file`

Commit body can be
> This Renames the file DuplicatefileBearTest.py
> to DuplicateFileBearTest.py
> ensuring that proper casing is done
>
> Closes https://github.com/coala/coala-bears/issues/2132

**Comment by gokberksahin** [comment]
I am not new to git but i didn't contribute to a open source project before.
I'm reading the newcomers guide now, thanks for your interest :+1:

**Comment by prashant0598** [comment]
@gokberksahin Read the newcomers guide thoroughly and if u have any doubt ping us on gitter. We will be happy to help and make pr only after reading newcomers guide.

**Comment by prashant0598** [comment]
unack dfd4c3d

**Comment by yashovardhanagrawal** [comment]
okay, so you have done the rebase and the commit description and message is alright
but you have messed up the in rebasing your commit, another commit from the upstream branch is also being reflected in your commit. Again I would say read the Git Tutorial

if there's any problem ask us we would here for sure 😄

**Comment by yashovardhanagrawal** [comment]
from the next time refrain from committing from your master branch, make an alternate branch for a specific PR

**Comment by gokberksahin** [comment]
I rebased my commit according the guide, what i did exactly wrong?

**Comment by yashovardhanagrawal** [comment]
can you tell me what exactly did you do?

while rebasing you also added the last commit in the upstream branch into you commit

that's why there's a problem here

**Comment by gokberksahin** [comment]
I kept the first one as "pick" and others "squash" as guide said.

**Comment by yashovardhanagrawal** [comment]
I think you picked up one from the upstream master

**Comment by yashovardhanagrawal** [comment]
now execute the following commands
`git reset --soft HEAD^`
`git pull upstream master`

then commit your changes

**Comment by gokberksahin** [comment]
I can't push it says: because Updates were rejected because the tip of your current branch is behind its remote counterpart. Should i use `git pull origin master` ?

**Comment by yashovardhanagrawal** [comment]
use force push
`git push origin +master`

**Comment by gokberksahin** [comment]
It should be OK now?

**Comment by yashovardhanagrawal** [comment]
although I have approved it, from next time, keep in mind to 
give a PR description also (you might add it now) and 
not commit from the master branch (you cannot change that now)

**Comment by SanketDG** [comment]
ack 93fd0e5

**Comment by SanketDG** [comment]
@rultor merge

**Comment by gokberksahin** [comment]
Merge has failed. Can someone try to merge again?

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Pull request merged**
