### PR TITLE
.travis.yml: Pre-install apt packages

### PR DESCRIPTION
**Pull request by jayvdb**
Closes https://github.com/coala/coala-bears/issues/2539

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by yukiisbored** [comment]
ack https://github.com/jayvdb/coala-bears/commit/879c62940b13aa3a8ae812d0755cef19b8fbf543

**Comment by yukiisbored** [comment]
@gitmate-bot ff

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/2538/commits/eadecf0d5fdb76beed6372b0a128df8e46ce0554

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/2538/commits/e30205cfecb3b14d94b25d4d261f9fc35bdbd1bb

**Comment by yukiisbored** [comment]
@gitmate-bot ff

**Comment by jayvdb** [comment]
I got it. :P  I am currently rebasing and merging https://github.com/coala/coala-bears/pull/2542 .  Will do this after it.

**Comment by jayvdb** [comment]
reack https://github.com/coala/coala-bears/pull/2538/commits/64e95b3022865bdfdcdb637557962dda5d6cafe4 https://github.com/coala/coala-bears/pull/2538/commits/ed70cccffdfa5a04325e40dc08969aef9e618428

**Comment by jayvdb** [comment]
See follow up notice at https://github.com/coala/coala-bears/issues/2539#issuecomment-397692039

The objective of this issue / PR is to move the apt installs to travis' managed list.

**Pull request merged**
