### PR TITLE
bears/gettext: Add DennisBear

### PR DESCRIPTION
**Pull request by sils**
Linter bear for translated PO and POT files.

Closes https://github.com/coala/coala-bears/issues/892

### CODE REVIEW

**Comment by sils** [comment]
reack https://github.com/coala/coala-bears/pull/1281/commits/9c1a0bf1f9a77c67b0bee14b2222ed843ddd5520

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
@Flap-Py so we get this merged after all :)

**Comment by jayvdb** [comment]
Just noting that this was done in https://github.com/coala/coala-bears/pull/1147 , but that PR was borked for unknown reasons and no response at https://github.com/travis-ci/travis-ci/issues/7111 .

**Comment by sils** [comment]
@jayvdb sorry not getting you fully?

I contacted travis via mail about the issue, let's see if something happens.

**Comment by sils** [comment]
ah gotcha

**Pull request merged**
