### PR TITLE
package.json.jinja2: Remove redundant line

### PR DESCRIPTION
**Pull request by Hori75**
Removes a redundant line in .ci/package.json.jinja2
Closes https://github.com/coala/coala-bears/issues/2388

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by Hori75** [comment]
Done, commit message edited.

**Comment by anctartica** [comment]
No. Have you read this https://api.coala.io/en/latest/Developers/Writing_Good_Commits.html?@Hori75  Change your commit message accordingly

**Comment by Hori75** [comment]
I haven't read that guide before, thanks for the guide.

**Comment by stellargo** [comment]
ack 509a9e3887aa975b8067bc772c9b80b4eefae2ff

**Comment by jayvdb** [comment]
ack 509a9e3

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Pull request merged**
