### PR TITLE
CheckstyleBearTest: Use assertRaisesRegex

### PR DESCRIPTION
**Pull request by jayvdb**
Check the AssertionError exception message.

Addresses https://github.com/coala/coala-bears/issues/1194

### CODE REVIEW

**Comment by Nosferatul** [comment]
Everything looks ok, but we need appveyor to be runed.

**Comment by jayvdb** [comment]
Instead of "Addresses", maybe "Implements"?
The idea being that many PRs may be desirable to implement a conceptual issue before it is closed.

**Comment by Mixih** [comment]
yeah, I'd say either `implements` or `related to`

**Comment by jayvdb** [comment]
Switched to "Related to "

**Comment by yukiisbored** [comment]
ack https://github.com/coala/coala-bears/pull/1196/commits/a22bdea3355edc11cb068c60190909d4eb96e47c

**Comment by jayvdb** [comment]
reack d79a8df

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
