### PR TITLE
RELEASE_NOTES.rst: Fixes a warning that was thrown.

### PR DESCRIPTION
**Pull request by arghyatiger**
converts Named hyperlink
 references
to anonymous hyperlink 
references

fixes https://github.com/coala/coala-bears/issues/1046

### CODE REVIEW

**Comment by Mixih** [comment]
You need to fix your git shortlog. The first letter after the colon `:` must be a capital letter

**Comment by Nosferatul** [comment]
How this solve the problem?

**Comment by sils** [comment]
describe your change in the message, not the issue you fix! More like "Make link anonymous" or something and then describe in the body exactly what this fixes and why

**Comment by Mixih** [comment]
@arghyatiger Ping? Also, the commit body formatting is really weird....

**Comment by yash-nisar** [comment]
@arghyatiger Are you still on it ?

**Comment by Mixih** [comment]
@arghyatiger PING! This issue is rather important as it is a block to enabling rstcheckers on all of our rsts.

**Comment by arghyatiger** [comment]
yes i am on it . will do it soon

**Comment by Nosferatul** [comment]
closing due to high inactivity

**Pull request closed without merging**
