### PR TITLE
Removed trailing spaces

### PR DESCRIPTION
**Pull request by ke2ulpatani**

### CODE REVIEW

**Comment by sils1297** [comment]
Hi,

We just dployed a fix to what's causing your builds to fail - you can get thm on your branch with a rebase. [This page](http://coala.io/git) may help you to get started on this. (*Do not press the update branch button. It's evil.*) The rebase should fix the build!

Add the original coala repository as a remote:

```
git remote add upstream https://github.com/coala/coala-bears.git
```

Then go to your branch and rebase it onto our master:

```
git checkout <yourbranch>
git fetch upstream
git rebase --interactive upstream/master
```

Now push it up. You will need to do a force push because you change history here (do not do this on master branches :)):

```
git push --force
```

If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix it up for you - just tell us :).

Ping us on [our gitter channel](https://coala.io/chat) if you need help!

**Comment by Adrianzatreanu** [comment]
bump @ke2ulpatani

**Comment by sils** [comment]
@ke2ulpatani what was the purpose of this PR? Was there any particular problem with this?

**Comment by jayvdb** [comment]
No longer needed.

**Pull request closed without merging**
