### PR TITLE
requirements: Require coala 0.9.1+

### PR DESCRIPTION
**Pull request by jayvdb**
coala-bears 0.9 should not be used with coala 0.10

### CODE REVIEW

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1243/commits/aa76d08a1877669f5925805556f38320cc91838d

(For the release we'll switch that to 0.10 anyways, this is actually a good sign, we didn't break API in coala and the bears this release yet :) latest with @Makman2 's changes we'll have to upgrade to 0.10 or 11 dependent on whats the newest then)

**Comment by jayvdb** [comment]
The requirement could also be 0.9.0+ , but I expect we'll at least coala 0.9.1 for `UnknownLanguage` due to https://github.com/coala/coala-bears/pull/1100

**Comment by Nosferatul** [comment]
ack  	120bed0

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
reack aa76d08

**Comment by sils** [comment]
reack aa76d08

**Comment by sils** [comment]
ack 120bed0

**Comment by jayvdb** [comment]
@rultor merge

**Pull request merged**
