### PR TITLE
setup.py: Change url to http://coala.io/

### LINKED ISSUE #2135: Set setup.py url = http://coala.io/
difficulty/newcomer
Opened by @jayvdb at [Gitter](https://gitter.im/coala/coala?at=5a1181aff257ad9109b396a0)

### PR DESCRIPTION
**Pull request by urohit011**
Changed url to 'http://coala.io/' in setup.py.

closes #2135 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by jayvdb** [comment]
unack https://github.com/coala/coala-bears/pull/2136/commits/6dbfe966114a4da4f2cf9dc817dcc8f72ef81842

**Comment by urohit011** [comment]
@jayvdb, what do I need to do.

**Comment by jayvdb** [comment]
fix the commit message, see our developer guide

**Comment by mridubhatnagar** [comment]
setup.py: Change url

Changed url from 'http://coala.rtfd.org/'
to 'http://coala.io/'.

Closes <issue-link>

**Comment by khanchi97** [comment]
ack f32b4c2

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Pull request merged**
