### PR TITLE
.gitignore: Add ignore rule for package-lock.json

### PR DESCRIPTION
**Pull request by binore**
This adds ignore rule for package-lock.json

Fixes https://github.com/coala/coala-bears/issues/2383

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by palash25** [comment]
Amend the commit message to `.gitignore: Add ignore ......`

And also add an issue link in the commit description

And read this for future reference http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by binore** [comment]
Done.

**Comment by jayvdb** [comment]
Need rebase

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2494/commits/213d3ae7b746cdad82e637197dc2a9a3d3b4a0f1

**Comment by jayvdb** [comment]
@gitmate-bot ff

**Pull request merged**
