### PR TITLE
PyLintBear: PyLintBear breaks on Python `3.5.0`

### PR DESCRIPTION
**Pull request by sangamcse**
This upgrade `pylint` to `1.7.2`
and fixes the PylintBear breaks on Python `3.5.0`

Closes https://github.com/coala/coala-bears/issues/1973

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by sangamcse** [comment]
1.8.2 is not stable version of pylint. I read the pylint documentation. So,
decided to stick with 1.7.2. Maybe we can move to new updates when it has
stable updates. 😀

**Comment by newbazz** [comment]
You checked that the latest stable version is `1.7.2` ?

**Comment by sangamcse** [comment]
Yes

**Comment by nvzard** [comment]
@sangamcse tests will pass with lower versions. The job was to update pylint to the latest pip release. I myself spent quite a lot of time figuring what is going wrong and reading the documentation but still, I'm not moving anywhere forward. Let's see what maintainers have to say about this issue.

**Comment by sangamcse** [comment]
@nvzard This PR was to fix the `PylintBear breaks on Python 3.5.0`. BTW I was not updating pylint to the latest pip release. However, 1.7.2 is latest stable pip release.

**Comment by nvzard** [comment]
@sangamcse ohk, no issues. I was talking about the issue I was working on https://github.com/coala/coala-bears/issues/2180

**Comment by nvzard** [comment]
btw can you please point out where it says in the documentation that the latest release 1.8.2 is not stable, I've read the documentation and changelogs more than once but might have missed something :P 
If its not stable for some reason you might file an issue in the PyLint repo.

**Comment by sangamcse** [comment]
@Makman2, modified as per your review.

**Comment by Makman2** [comment]
ack 5a4115ec125a58423c6d732d5bb03b5c496c10f5

**Comment by Makman2** [comment]
@gitmate-bot ff

**Pull request merged**
