### PR TITLE
VultureBear: Add SEE_MORE attribute

### PR DESCRIPTION
**Pull request by RJ722**
### Checklist

- [X] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [X] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by RJ722** [comment]
Can you please `ack` the commit? 😄

**Comment by damngamerz** [comment]
ack 52f534e0fcedabf561c0a35dbd27a195d031ff30

**Comment by meetmangukiya** [comment]
ack 52f534e0fcedabf561c0a35dbd27a195d031ff30

**Comment by meetmangukiya** [comment]
@rultor merge!

**Pull request merged**
