### PR TITLE
Update Jinja2Bear.py

### PR DESCRIPTION
**Pull request by Naereen**
- Added link to Jinja website in the documentation.

### CODE REVIEW

**Comment by sils** [comment]
Hi,

it seems that your commit message doesn't contain enough information. Don't worry, most people don't know about good commit messages when they join us, including very experienced developers :) Standards vary from project to project.

The most important part is the first line of your commit message - maintainers will use it to read through a large number of commits and thus it's important that it's short but most importantly concise. I'd heartily recommend reading <http://coala.io/commit>!

To change your message you just use `git commit --amend` and then `git push --force` the new commit to replace the old one.

**If you're just looking to fix an issue very quickly and not interested in contributing to coala long term, we can fix up the message for you - just tell us :).**

Cheers!

**Comment by sils** [comment]
please note that to fix the gitmate issues you have to amend your commit locally, same thing applies: if you find this tedious and don't want to long term contribute, we can help

**Comment by fneu** [comment]
The changes itself are all correct and welcome though, thanks :)

If you amend your commit with the line breaks requested by GitMate and alter the commit message, this should be fine.

If you close an Issue with this commit, please mention it in the commit message.

**Comment by Naereen** [comment]
Not closing any issue.
Now it should be fine, I merged the suggestions by @gitmate-bot.

**Comment by Naereen** [comment]
And indeed I was not especially looking to start a long-term contribution, just wanted to fix this link issue.

By the way, it seems that the same issue appear on, well, almost every documentation.

**Comment by Naereen** [comment]
I don't understand why @gitmate-bot still sends me emails about the issues I just fixed.

**Comment by sils** [comment]
@Naereen since you're not intending to contribute long term, don't worry, I can fix it up. GitMate will analyze every commit on it's own so the history isn't cluttered by "fixup" commits.

**Comment by aptrishu** [comment]
Squash your commits.

**Comment by aptrishu** [comment]
Needs modification in commit message. See https://coala.io/commit
Also gitmate fixes don't require an extra commit.

**Comment by sils** [comment]
@Naereen I made https://github.com/coala/coala-bears/pull/1278 for you keeping you as author, thanks for your help! I can understand that the contribution process is a bit intimidating which is why we're doing this we-get-your-stuff-merged-for-you service ;)

**Comment by Naereen** [comment]
OK, as you wish. Thanks.

**Pull request closed without merging**
