### PR TITLE
PythonPackageInitBear.py: Moved docstring from class to 'run' method

### PR DESCRIPTION
**Pull request by naman1901**
Moved docstring from class to 'run' method to fix issue [ #1500 ](https://github.com/coala/coala-bears/issues/1500)

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by naman1901** [comment]
Hi. This is my first ever contribution to Open Source. I can see there are some issues with my PR. Any tips on how to identify these beforehand and avoid them cropping up in only when my PR is being checked?

**Comment by yash-nisar** [comment]
Sure, go through http://api.coala.io/en/latest/Developers/Newcomers_Guide.html and http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html

**Comment by naman1901** [comment]
Thanks. Had read through the first doc, will read up the second. So should I close this now and submit another PR when I've fixed the changes?

**Comment by yash-nisar** [comment]
No, its okay to make mistakes in the beginning. You can carry on with this PR and modify your commit by `git commit --amend` and then force push by `git push -f remote branchname`

**Comment by yash-nisar** [comment]
You can contact us on gitter if you still face any issues. :)

**Comment by naman1901** [comment]
Messed up a bit, will issue a new PR soon.

**Pull request closed without merging**
