### PR TITLE
Try to fix master

### PR DESCRIPTION
**Pull request by nemaniarjun**
Removed apt package which set java version to 9.

### CODE REVIEW

**Comment by nemaniarjun** [comment]
@sils this is urgent. 
Some test was skipped.
Need your input on this.

**Comment by Mixih** [comment]
@nemaniarjun that skip has been happening for a month so it's not regression.

**Comment by sils** [comment]
ack https://github.com/coala/coala-bears/pull/1279/commits/9d9c018be2a56b1c8ea5ff3fca0dd0f80cc37283

**Comment by sils** [comment]
@rultor merge

**Pull request merged**
