### PR TITLE
Fix #1081 - Add Asciinema for GofmtBear

### LINKED ISSUE #1081: GofmtBear: Add advanced asciinema
The coala bear GofmtBear does not have a proper asciinema.

`gofmt` is a command line tool that automatically solves formatting / styling issues to the absolute coding style that Go has.

I'm planning to use a working code as the sample where it's filled with mixed indentation (spaces and tabs), semicolons and demonstrate how gofmt formats the code automatically and correctly to the absolute Go coding style.

### PR DESCRIPTION
**Pull request by yukiisbored**
It's nice to see how the bear works and see it in action. Therefore,
it's a good idea to have a demo for this bear.

This commit demostrate GofmtBear by using a sample that has a couple
of "classic" formatting issues such as mixed indentation and semi
colons.

### CODE REVIEW

**Comment by Nosferatul** [comment]
Please check coala.io/commit and update it. Also delete first 2 lines from the commit message, we don't need them

**Comment by sils** [comment]
yep, everything good except commit message 👍

**Comment by yukiisbored** [comment]
@sils @Nosferatul Thanks for the suggestions. I forgot to read the commit part of the docs, Thanks for the reminder! I've fixed the problems.

**Comment by sils** [comment]
Nice, one last thing: Replace your Fixes with a Closes, we use that for bug prediction.

**Comment by yukiisbored** [comment]
@sils There you go, sorry for the long pause.

**Comment by sils** [comment]
you're very responsive ;) No need to apologize for delays when working on open source projects.

https://github.com/coala/coala-bears/pull/1082/commits/aa43737b06ccdff8fd4d60be67d09ba4a05bbc65 is ready

**Comment by sils** [comment]
@rultor merge

**Comment by sils** [comment]
Hey, this is your first contribution, right? Congrats and welcome to the coalaians! :)

You can help us a lot by filling out <http://coala.io/newform>!

Rultor will now automatically release your changes as a prerelease so users can experience the goodness of your changes right now.

See also https://github.com/coala-analyzer/coala/wiki/coala-Steam-Offer btw.

**Pull request merged**
