### PR TITLE
Change stable version to 0.10.0

### PR DESCRIPTION
**Pull request by AGZ98**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by satwikkansal** [comment]
ack 8a1f37

**Comment by satwikkansal** [comment]
@AGZ98 There's already another PR for this https://github.com/coala/coala-bears/pull/1430 , you should first assign yourself to an issue and then work on it to avoid redundancy and hence the time wasted :wink: If there's not an existing issue for your change, then create one, assign yourself to it and then submit a PR :)

**Comment by sahilarora535** [comment]
unack 8a1f37e8db267a8e641cf58edc5b0a09ab8c660b

**Comment by sahilarora535** [comment]
There is already an issue regarding this: https://github.com/coala/coala-bears/issues/1408
And it's pre-assigned. Please assign an issue to yourself before working on it, so that no two people work on this simultaneously. Check out the newcomers' guide [here](https://api.coala.io/en/latest/Developers/Newcomers_Guide.html#newcomer-guide).

**Comment by sahilarora535** [comment]
@aptrishu The issue has already been assigned to someone. https://github.com/coala/coala-bears/issues/1408

**Comment by AGZ98** [comment]
Sorry! I was working on this issue in under coala/coala.. I accidently submitted it to coala/coala-bears too

**Comment by meetmangukiya** [comment]
> Sorry! I was working on this issue in under coala/coala.. I accidently submitted it to coala/coala-bears too

Ok, closing it

**Pull request closed without merging**
