### PR TITLE
CPPCleanBear.py: Added include_path for header files

### PR DESCRIPTION
**Pull request by stellargo**
The feature for allowing include_path was added so the user can include paths for header files for cppclean. Only one include_path can be specified in the .coafile with this commit and the ability to add more include_path has not been added yet.

References https://github.com/coala/coala-bears/issues/2026

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [ ] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [ ] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by stellargo** [comment]
Hey @palash25 thanks for the comment but you see this is WIP(work in progress) tagged PR. I am still working on it and this isn't ready for review.
Also regarding the no of commits, you might want to have a look at 'what makes a good commit' http://api.coala.io/en/latest/Developers/Writing_Good_Commits.html
Once I have completely finished working on this, would love to hear your inputs :)

**Comment by jayvdb** [comment]
This one grew legs and became https://github.com/coala/coala-bears/pull/2037

**Comment by stellargo** [comment]
@jayvdb This was half a year back when I was new to git 😅 Apologies :)

**Comment by jayvdb** [comment]
No worries... im just going through everyones PRs. One more check with 24 hrs to go :P

**Pull request closed without merging**
