### PR TITLE
GitCommitBearTest.py: Fix docstring typo

### PR DESCRIPTION
**Pull request by farberbrodsky**
messgae --> message

Fixes https://github.com/coala/coala-bears/issues/2304

### CODE REVIEW

**Comment by Naveenaidu** [comment]
Please don't work on your master. You will eventually have to make a seperate branch and reference this PR there. Go through the http://api.coala.io/en/latest/Developers/Newcomers_Guide.html. Otherwise the changes LGTM.

**Comment by farberbrodsky** [comment]
Should I do it again from a branch?

**Comment by Naveenaidu** [comment]
Yes! That would be great.

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
You deleted your fork.  This PR is now broken. ;-(

**Comment by jayvdb** [comment]
Please follow the coala procedures more carefully next time.

**Pull request closed without merging**
