### PR TITLE
TravisLintBearTest.py: Close opened files properly

### LINKED ISSUE #2042: TravisLintBearTest: Close opened test files properly
py.test gives warnings on https://circleci.com/gh/coala/coala-bears/7126 like
```
tests/yaml/TravisLintBearTest.py::TravisLintBearTest::test_good_file
  /home/ubuntu/coala-bears/tests/yaml/TravisLintBearTest.py:23: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/ubuntu/coala-bears/tests/yaml/travislint_test_files/.good_travis.yml' mode='r' encoding='UTF-8'>
    return open(get_testfile_path(name)).readlines()
```
To not rely on ref-counting for object destruction (which isn't anyway an official feature in Python to allow custom destructors), we should close the file manually by using a with-context:
```
with open(get_testfile_path(name)) as fl:
    return fl.readlines()
```

### PR DESCRIPTION
**Pull request by anuyog1004**
This closes opened test files properly using a with-context

Closes #2042

### CODE REVIEW

**Comment by mridubhatnagar** [comment]
Also in cases where the first line is sufficient to describe what the PR is about. In those PR's commit description can be skipped.

**Comment by mridubhatnagar** [comment]
You'll have to amend your commit message using git commit --amend

**Comment by anuyog1004** [comment]
Hi @mridubhatnagar, I will update the commit message.
Can you also tell me what "Your tests failed on CircleCI" means

**Comment by RaiVaibhav** [comment]
@anuyog1004 Please provide a full issue reference

**Comment by RaiVaibhav** [comment]
In Commit message Head use `TravisLintBearTest.py` instead of `TravisLintBearTest`

**Comment by mridubhatnagar** [comment]
ack 1fb6b4a

**Comment by Makman2** [comment]
ack 1fb6b4a

**Comment by Makman2** [comment]
@gitmate-bot rebase

**Pull request merged**
