### PR TITLE
openSUSE package version sync

### PR DESCRIPTION
**Pull request by jayvdb**
- PyFlakesBear: Bump dependency pyflakes~=1.5.0
- YapfBear: Bump dependency yapf~=0.16.0

Related to https://github.com/coala/docker-coala-base/issues/196

### CODE REVIEW

**Comment by Nosferatul** [comment]
ack 6ccee8a 23d974a

**Comment by Nosferatul** [comment]
@jayvdb please rebase

**Comment by NiklasMM** [comment]
Was cherry-picked and will be merged with https://github.com/coala/coala-bears/pull/1930

**Comment by jayvdb** [comment]
Please dont cherry-pick maintainer PRs.  They are able to re-ack and merge any time.

**Comment by NiklasMM** [comment]
Uhm, ok. They are still using CI resources though. 

Do you want me to remove the commits from the cp branch?

**Comment by jayvdb** [comment]
reack 4bad88a 18faa04

**Comment by jayvdb** [comment]
@rultor merge

**Comment by jayvdb** [comment]
Ah fuck, cancelling the extra build turns Travis CI red; despite it having been green after the first build was successful.

**Comment by jayvdb** [comment]
ah, woot.  rultor accepted it anyway.

**Pull request merged**
