### PR TITLE
PySafetyBear.py: Adds Asciinema for PySafetyBear.

### LINKED ISSUE #2371: PySafetyBear: Add asciinema
Content of file on Bear will perform it's action also have to shown in asciinema.

difficulty/newcomer

### PR DESCRIPTION
**Pull request by arnav-mandal1234**
Adds asciinema for PySafetyBear.

Previously, no asciinema was present in PySafetyBear.py file.
Adds asciinema for PySafetyBear.

Fixes #2371 

**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `corobo mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Comment by arnav-mandal1234** [comment]
Kindly check. I have made the following changes. @li-boxuan @shashank-b @budukhyash

**Comment by arnav-mandal1234** [comment]
@shashank-b I have seen some commits on the same type of issue. They have the similar type of commit message.
For example:
https://github.com/coala/coala-bears/commit/25bd79a54eb0e90c03085e091fd1757bd38b3239
https://github.com/coala/coala-bears/commit/b5583395ea98567c324416fee9d0fce9f616685f

**Comment by arnav-mandal1234** [comment]
Kindly check now. @RaiVaibhav @frextrite @li-boxuan

**Comment by shashank-b** [comment]
Hint: `Add asciinema...` -->  `This adds asciinema...`

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
@gitmate-bot rebase

**Comment by jayvdb** [comment]
ack https://github.com/coala/coala-bears/pull/2837/commits/5b6de3e0e68f61e54866398855604ddeb630a2b2

**Pull request merged**
